/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState } from 'react';
import { coverage, differences, publishedAssignments, validateRoster } from '@/lib/m08/planning.mjs';
import { csvExport, reportRows } from '@/lib/m08/reports.mjs';
import { exportM08 } from '@/lib/m08/functions';
import { Button, CanButton, DataList, Decision, EditDialog, Fields, Panel, Status, useM08, useText } from './common';
import { opts, parseRef, refs, textField, type Field, type Row } from './forms';
import { RosterPicker, useSelectedRoster } from './Rosters';
import { authHeaders } from './Definitions';
const utc = (value: string) => value ? value + (value.length === 16 ? ':00Z' : /Z$/.test(value) ? '' : 'Z') : value;
const REPORT_OPTIONS = [
  ['rosters', 'الجداول', 'Rosters'], ['coverage', 'التغطية', 'Coverage'], ['planned_actual', 'المخطط والفعلي', 'Planned vs actual'],
  ['night_distribution', 'توزيع الليالي', 'Night distribution'], ['published_changes', 'التغييرات بعد النشر', 'Published changes'],
  ['swaps', 'التبديل والتنازل', 'Swaps and transfers'], ['overtime', 'الإضافي', 'Overtime'], ['cost_centers', 'مراكز التكلفة', 'Cost centers'],
  ['results', 'نتائج الحضور', 'Attendance results'], ['requests', 'الطلبات', 'Requests'], ['deliveries', 'التسليم للرواتب', 'Payroll deliveries'], ['audit', 'التدقيق', 'Audit'],
];
const REPORT_COLUMNS: Record<string, [string, string]> = {
  employeeId: ['الموظف', 'Employee'], employeeCode: ['رقم الموظف', 'Employee code'], branch: ['الفرع', 'Branch'], siteCode: ['الموقع', 'Site'],
  workDate: ['يوم العمل', 'Work date'], workDates: ['أيام العمل', 'Work dates'], plannedMinutes: ['دقائق مخططة', 'Planned minutes'],
  actualMinutes: ['دقائق فعلية', 'Actual minutes'], paidMinutes: ['دقائق مدفوعة', 'Paid minutes'], missingMinutes: ['دقائق ناقصة', 'Missing minutes'],
  nights: ['الليالي', 'Nights'], night: ['ليلي', 'Night'], headcount: ['عدد الموظفين', 'Headcount'],
  plannedAssignments: ['فترات مخططة', 'Scheduled periods'], recordedAssignments: ['فترات محسوبة', 'Calculated periods'],
  unconfirmedAssignments: ['فترات لم تعتمد نتائجها', 'Unconfirmed periods'],
  costCenter: ['مركز التكلفة', 'Cost center'], shiftCode: ['رمز الشفت', 'Shift code'], dayType: ['نوع اليوم', 'Day type'],
  status: ['الحالة', 'Status'], approval: ['الاعتماد', 'Approval'], source: ['المصدر', 'Source'], reason: ['السبب', 'Reason'],
  periodNo: ['رقم الفترة', 'Period'], version: ['الإصدار', 'Version'], start: ['البداية', 'Start'], end: ['النهاية', 'End'],
  plannedOvertime: ['إضافي مخطط', 'Planned OT'], observedOvertime: ['إضافي مرصود', 'Observed OT'],
  eligibleOvertime: ['إضافي مؤهل', 'Eligible OT'], approvedOvertime: ['إضافي معتمد', 'Approved OT'],
};
export function Coverage() {
  const { state, command } = useM08(), t = useText(); const { roster, list, setId } = useSelectedRoster(); const [editing, setEditing] = useState<Row | null>(null);
  const result = coverage(state, roster?.assignments ?? publishedAssignments(state), state.demands.filter((d: Row) => !roster || d.workDate >= roster.from && d.workDate <= roster.to));
  return <Panel title={t('الاحتياج حسب الموقع والوقت والمهارة', 'Demand by site, time and skill')}><RosterPicker list={list} roster={roster} onChange={setId} />
    <CanButton action="draft" onClick={() => setEditing({ minimum: 0, target: 0, maximum: 0, severity: 'blocker' })}>{t('إضافة احتياج', 'Add demand')}</CanButton>
    <p className="text-sm">{t('كل موظف يغطي مكانًا واحدًا في الوقت نفسه. الاستراحات وعدم التوافر يقللان التغطية.', 'Each employee covers one concurrent position. Breaks and unavailability reduce coverage.')} · {result.ratio == null ? t('لا يوجد احتياج', 'No demand') : `${result.ratio.toFixed(1)}%`}</p>
    <DataList rows={result.segments} columns={[{ key: 'siteCode', label: ['الموقع', 'Site'] }, { key: 'skill', label: ['المهارة', 'Skill'] }, { key: 'start', label: ['من', 'From'] }, { key: 'end', label: ['إلى', 'To'] }, { key: 'minimum', label: ['الأدنى', 'Minimum'] }, { key: 'target', label: ['المستهدف', 'Target'] }, { key: 'maximum', label: ['الأقصى', 'Maximum'] }, { key: 'assigned', label: ['المغطى', 'Covered'] }, { key: 'gap', label: ['النقص', 'Gap'] }, { key: 'available', label: ['المؤهل المتاح', 'Available qualified'] }]} />
    <DataList rows={state.demands} columns={[{ key: 'workDate', label: ['التاريخ', 'Date'] }, { key: 'siteCode', label: ['الموقع', 'Site'] }, { key: 'skill', label: ['المهارة', 'Skill'] }, { key: 'target', label: ['المستهدف', 'Target'] }]} actions={d => <CanButton action="draft" entity={d} onClick={() => setEditing({ ...d, start: d.start.slice(0, 16), end: d.end.slice(0, 16) })}>{t('تعديل', 'Edit')}</CanButton>} />
    {editing && <EditDialog title={t('احتياج التغطية', 'Coverage demand')} initial={editing} fields={[textField('workDate', 'تاريخ العمل', 'Work date', 'date'), { ...textField('siteCode', 'الموقع', 'Site', 'select'), options: state.sites.map((s: Row) => ({ value: s.code, label: s.nameAr })) }, textField('branch', 'رمز الفرع', 'Branch code'), textField('skill', 'رمز المهارة', 'Skill code', 'text', false), textField('start', 'البداية UTC', 'Start UTC', 'datetime-local'), textField('end', 'النهاية UTC', 'End UTC', 'datetime-local'), textField('minimum', 'أقل عدد', 'Minimum', 'number'), textField('target', 'العدد المستهدف', 'Target', 'number'), textField('maximum', 'أقصى عدد', 'Maximum', 'number'), { ...textField('severity', 'شدة النقص', 'Shortage severity', 'select'), options: opts(['warning', 'exception', 'blocker']) }, textField('costCenter', 'مركز التكلفة', 'Cost center', 'text', false)]} onClose={() => setEditing(null)} onSave={(value, reason) => command('demand.save', { value: { ...value, start: utc(value.start), end: utc(value.end) } }, reason)} />}
  </Panel>;
}
export function SelfService({ open = false }: { open?: boolean }) {
  const { state, actor, command, lang } = useM08(), t = useText(); const [dialog, setDialog] = useState<Row | null>(null); const me = state.employments.find((e: Row) => e.userId === actor.id);
  const assignments = publishedAssignments(state), myAssignments = assignments.filter(a => a.employeeId === me?.employeeId && a.dayType === 'WORK');
  const colleagueOptions = state.swapOptions ?? [];
  const describe = (a: Row) => `${a.employeeCode || ''} · ${a.workDate} · ${a.shift?.code || a.shiftCode || ''} · ${a.start || ''}`;
  return <Panel title={open ? t('الشواغر وطلبات شغلها', 'Open shifts and applications') : t('التغيير والتبادل والتنازل', 'Changes, swaps and transfers')}>
    {open ? <><CanButton action="draft" onClick={() => setDialog({ kind: 'createOpen' })}>{t('فتح شاغر', 'Create vacancy')}</CanButton><DataList rows={state.openShifts} columns={[{ key: 'workDate', label: ['تاريخ العمل', 'Work date'] }, { key: 'siteCode', label: ['الموقع', 'Site'] }, { key: 'skill', label: ['المهارة', 'Skill'] }, { key: 'slots', label: ['الأماكن', 'Slots'] }, { key: 'deadline', label: ['آخر موعد', 'Deadline'] }, { key: 'status', label: ['الحالة', 'Status'], render: r => <Status value={r.status} /> }]} actions={o => <CanButton action="request" entity={me} disabled={!me || o.status !== 'open'} onClick={() => setDialog({ kind: 'decision', title: t('طلب شغل الشاغر', 'Apply for open shift'), action: 'request.create', payload: { kind: 'open', employeeId: me.employeeId, openId: o.id } })}>{t('طلب الشاغر', 'Apply')}</CanButton>} /></> : <CanButton action="request" entity={me} disabled={!me} onClick={() => setDialog({ kind: 'createRequest' })}>{t('طلب جديد', 'New request')}</CanButton>}
    {!me && <p className="text-sm text-muted-foreground">{t('يلزم ربط حسابك بارتباط الموظف لاستخدام الطلبات الشخصية.', 'Link your account to an employee employment record to submit personal requests.')}</p>}
    <DataList rows={state.requests} columns={[{ key: 'kind', label: ['نوع الطلب', 'Type'] }, { key: 'employeeId', label: ['الموظف', 'Employee'] }, { key: 'at', label: ['تاريخ الطلب', 'Requested at'] }, { key: 'status', label: ['الحالة', 'Status'], render: r => <Status value={r.status} /> }, { key: 'managerApprovals', label: ['مراحل اعتماد المدير', 'Manager approval stages'], render: r => `${r.managerApprovals?.length ?? 0} / ${[r.rosterId, r.otherRosterId].filter((id: string, i: number, a: string[]) => id && a.indexOf(id) === i).reduce((n: number, id: string) => { const roster = state.rosters.find((x: Row) => x.id === id); return n + (state.policies.find((p: Row) => p.id === roster?.policyId && p.version === roster?.policyVersion)?.approvalRoles.length ?? 0); }, 0)}` }, { key: 'reason', label: ['السبب', 'Reason'] }]} actions={r => <>
      {r.otherEmployeeId === me?.employeeId && r.status === 'peer_pending' && <><Button onClick={() => setDialog({ kind: 'decision', title: t('قبول طلب الزميل', 'Accept colleague request'), action: 'request.peer', payload: { id: r.id, accept: true } })}>{t('قبول', 'Accept')}</Button><Button onClick={() => setDialog({ kind: 'decision', title: t('رفض طلب الزميل', 'Reject colleague request'), action: 'request.peer', payload: { id: r.id, accept: false } })}>{t('رفض', 'Reject')}</Button></>}
      <CanButton action="request_approve" entity={state.employments.find((e: Row) => e.employeeId === r.employeeId)} disabled={r.status !== 'review'} onClick={() => setDialog({ kind: 'decision', title: t('اعتماد المرحلة؛ النشر بعد اكتمال كل الموافقات وإعادة الفحص', 'Approve stage; publish after all approvals and revalidation'), action: 'request.approve', payload: { id: r.id } })}>{t('اعتماد المرحلة', 'Approve stage')}</CanButton>
      <CanButton action="request_approve" entity={state.employments.find((e: Row) => e.employeeId === r.employeeId)} disabled={r.status !== 'review'} onClick={() => setDialog({ kind: 'decision', title: t('رفض الطلب', 'Reject request'), action: 'request.reject', payload: { id: r.id } })}>{t('رفض', 'Reject')}</CanButton>
      {r.createdBy === actor.id && ['peer_pending', 'review', 'needs_review'].includes(r.status) && <Button onClick={() => setDialog({ kind: 'decision', title: t('سحب الطلب', 'Withdraw request'), action: 'request.withdraw', payload: { id: r.id } })}>{t('سحب', 'Withdraw')}</Button>}
    </>} />
    {dialog?.kind === 'decision' && <Decision {...dialog} onClose={() => setDialog(null)} />}
    {dialog?.kind === 'createRequest' && <EditDialog title={t('طلب شخصي', 'Personal request')} initial={{ kind: 'swap' }} fields={[
      { ...textField('kind', 'نوع الطلب', 'Request type', 'select'), options: opts(['swap', 'give', 'change']) }, { ...textField('assignmentKey', 'شفتك المنشور', 'Your published shift', 'select'), options: myAssignments.map(a => ({ value: a.key, label: describe(a) })) },
      { ...textField('otherAssignmentKey', 'شفت الزميل للمبادلة', 'Colleague shift to swap', 'select', false), options: colleagueOptions.map((a: Row) => ({ value: a.key, label: describe(a) })) },
      { ...textField('otherEmployeeId', 'الموظف المستلم للتنازل', 'Transfer recipient', 'select', false), options: colleagueOptions.map((a: Row) => ({ value: a.employeeId, label: a.employeeCode || a.employeeId })) },
      { ...textField('proposedShiftRef', 'الشفت البديل لطلب التغيير', 'Proposed replacement shift', 'select', false), options: refs(state.shifts, lang) },
    ]} onClose={() => setDialog(null)} onSave={(value, reason) => { const p = parseRef(value.proposedShiftRef), other = colleagueOptions.find((a: Row) => a.key === value.otherAssignmentKey); return command('request.create', { ...value, employeeId: me.employeeId, otherEmployeeId: value.kind === 'swap' ? other?.employeeId : value.otherEmployeeId, proposedShiftId: p.id, proposedShiftVersion: p.version }, reason); }} />}
    {dialog?.kind === 'createOpen' && <EditDialog title={t('شفت شاغر', 'Open shift')} initial={{ slots: 1 }} fields={[
      { ...textField('rosterId', 'الجدول المنشور', 'Published roster', 'select'), options: state.rosters.filter((r: Row) => r.status === 'published').map((r: Row) => ({ value: r.id, label: r.name })) }, textField('workDate', 'تاريخ العمل', 'Work date', 'date'), { ...textField('shiftRef', 'إصدار الشفت', 'Shift version', 'select'), options: refs(state.shifts, lang) }, { ...textField('siteCode', 'الموقع', 'Site', 'select'), options: state.sites.map((s: Row) => ({ value: s.code, label: s.nameAr })) }, textField('skill', 'المهارة', 'Skill', 'text', false), textField('slots', 'عدد الأماكن', 'Slots', 'number'), textField('deadline', 'آخر موعد UTC', 'Deadline UTC', 'datetime-local'),
    ]} onClose={() => setDialog(null)} onSave={(v, reason) => { const p = parseRef(v.shiftRef); return command('open.create', { ...v, shiftId: p.id, shiftVersion: p.version, deadline: utc(v.deadline) }, reason); }} />}
  </Panel>;
}
export function Exceptions() {
  const { state, command } = useM08(), t = useText(); const { roster, list, setId } = useSelectedRoster(); const [tab, setTab] = useState('schedule'), [dialog, setDialog] = useState<Row | null>(null);
  const employeeOptions = state.employments.map((e: Row) => ({ value: e.employeeId, label: `${e.code} · ${e.nameAr}` }));
  const assignments = publishedAssignments(state).filter(a => a.dayType === 'WORK');
  const decision = (action: string, payload: Row, title: string) => setDialog({ kind: 'decision', action, payload, title });
  const issueRows = roster ? validateRoster(state, roster) : [], before = state.rosters.find((r: Row) => r.id === roster?.baseId);
  return <div className="space-y-4"><Panel title={t('الاستثناءات والحضور وأثر التغيير', 'Exceptions, attendance and change impact')}>
    <div className="flex flex-wrap gap-2">{[['schedule', 'تعارضات الجدول', 'Roster conflicts'], ['attendance', 'حساب الحضور واعتماده', 'Calculate and approve attendance'], ['punches', 'البصمات والتصحيحات', 'Punches and corrections'], ['leaves', 'الإجازات والأذونات', 'Leave and permissions']].map(([key, ar, en]) => <Button key={key} primary={tab === key} onClick={() => setTab(key!)}>{t(ar!, en!)}</Button>)}</div>
    {tab === 'schedule' && <><RosterPicker list={list} roster={roster} onChange={setId} /><DataList rows={issueRows} columns={[{ key: 'code', label: ['القاعدة', 'Rule'] }, { key: 'severity', label: ['الشدة', 'Severity'] }, { key: 'message', label: ['التفاصيل', 'Details'] }]} actions={i => <CanButton action="exception" disabled={i.severity !== 'exception'} onClick={() => decision('exception.approve', { rosterId: roster.id, version: roster.version, issueKey: i.key }, t('اعتماد استثناء مسموح لهذه النسخة', 'Approve an allowed exception for this version'))}>{t('اعتماد الاستثناء', 'Approve exception')}</CanButton>} />
      <h3 className="font-bold">{t('الفروق عن النسخة المنشورة السابقة', 'Differences from previous publication')}</h3><DataList rows={differences(before?.assignments, roster?.assignments)} columns={[{ key: 'key', label: ['الإسناد', 'Assignment'] }, { key: 'before', label: ['قبل', 'Before'], render: d => d.before ? `${d.before.dayType} · ${d.before.shift?.code ?? ''} · ${d.before.start ?? ''} · ${d.before.siteCode}` : '—' }, { key: 'after', label: ['بعد', 'After'], render: d => d.after ? `${d.after.dayType} · ${d.after.shift?.code ?? ''} · ${d.after.start ?? ''} · ${d.after.siteCode}` : '—' }]} /><p className="text-xs text-muted-foreground">{t('الأثر المالي لا يكون نهائيًا قبل اكتمال البصمات واعتماد النتيجة. تصحيح دورة مقفلة ينتج تسوية مرتبطة بالأصل.', 'Financial impact is provisional until punches are complete and attendance approved. Closed-period corrections create linked adjustments.')}</p></>}
    {tab === 'attendance' && <><DataList rows={assignments} columns={[{ key: 'employeeCode', label: ['الموظف', 'Employee'] }, { key: 'workDate', label: ['التاريخ', 'Date'] }, { key: 'start', label: ['البداية', 'Start'] }, { key: 'end', label: ['النهاية', 'End'] }]} actions={a => <CanButton action="recalculate" entity={a} onClick={() => decision('attendance.calculate', { assignmentKey: a.key }, t('حساب الحضور من النسخة المنشورة', 'Calculate from the published roster'))}>{t('حساب', 'Calculate')}</CanButton>} />
      <DataList rows={state.results} columns={[{ key: 'employeeId', label: ['الموظف', 'Employee'] }, { key: 'workDate', label: ['اليوم', 'Day'] }, { key: 'version', label: ['الإصدار', 'Version'] }, { key: 'presenceMinutes', label: ['التواجد', 'Presence'] }, { key: 'actualMinutes', label: ['عمل فعلي', 'Actual work'] }, { key: 'paidMinutes', label: ['مدفوع', 'Paid'] }, { key: 'excusedMinutes', label: ['معفى', 'Excused'] }, { key: 'missingMinutes', label: ['ناقص', 'Missing'] }, { key: 'eligibleOvertimeMinutes', label: ['إضافي مؤهل', 'Eligible overtime'] }, { key: 'approvedOvertimeMinutes', label: ['إضافي معتمد', 'Approved overtime'] }, { key: 'issues', label: ['الاستثناءات', 'Exceptions'] }, { key: 'approval', label: ['الاعتماد', 'Approval'], render: r => <Status value={r.approval.status} /> }]} actions={r => <>
        <CanButton action="attendance_approve" entity={state.employments.find((e: Row) => e.employeeId === r.employeeId)} disabled={r.approval.status === 'approved'} onClick={() => decision('attendance.approve', { id: r.id }, t('اعتماد نتيجة الحضور', 'Approve attendance result'))}>{t('اعتماد', 'Approve')}</CanButton>
        <CanButton action="attendance_reopen" entity={state.employments.find((e: Row) => e.employeeId === r.employeeId)} disabled={r.approval.status !== 'approved'} onClick={() => decision('attendance.reopen', { id: r.id }, t('إعادة فتح النتيجة', 'Reopen result'))}>{t('إعادة فتح', 'Reopen')}</CanButton>
        <CanButton action="attendance_approve" entity={state.employments.find((e: Row) => e.employeeId === r.employeeId)} disabled={r.approval.status === 'approved'} onClick={() => setDialog({ kind: 'overtime', result: r })}>{t('اعتماد الإضافي', 'Approve overtime')}</CanButton>
      </>} /></>}
    {tab === 'punches' && <><CanButton action="punch" onClick={() => setDialog({ kind: 'punch' })}>{t('استلام بصمة خام', 'Receive raw punch')}</CanButton><p className="text-sm">{t('السجلات الخام لا تُستبدل. أي تصحيح له سبب وموافقة ومصدر مستقل.', 'Raw events are immutable. Corrections have a separate source, reason and approval.')}</p><DataList rows={state.punches} columns={[{ key: 'employeeId', label: ['الموظف', 'Employee'] }, { key: 'at', label: ['وقت الحدث', 'Event time'] }, { key: 'receivedAt', label: ['وقت الاستلام', 'Received at'] }, { key: 'kind', label: ['النوع', 'Kind'] }, { key: 'source', label: ['المصدر', 'Source'] }, { key: 'sourceEventId', label: ['معرف المصدر', 'Source event ID'] }]} actions={p => <CanButton action="correct" entity={state.employments.find((e: Row) => e.employeeId === p.employeeId)} onClick={() => setDialog({ kind: 'correction', punch: p })}>{t('طلب تصحيح', 'Request correction')}</CanButton>} />
      <DataList rows={state.corrections} columns={[{ key: 'punchId', label: ['البصمة الأصلية', 'Original punch'] }, { key: 'replacement', label: ['التصحيح', 'Correction'] }, { key: 'reason', label: ['السبب', 'Reason'] }, { key: 'status', label: ['الحالة', 'Status'], render: c => <Status value={c.status} /> }]} actions={c => <CanButton action="attendance_approve" entity={state.employments.find((e: Row) => e.employeeId === c.employeeId)} disabled={c.status !== 'pending'} onClick={() => decision('correction.approve', { id: c.id }, t('اعتماد التصحيح بمراجع مستقل', 'Independent correction approval'))}>{t('اعتماد', 'Approve')}</CanButton>} /></>}
    {tab === 'leaves' && <><CanButton action="leave" onClick={() => setDialog({ kind: 'leave' })}>{t('استلام إجازة أو إذن للمراجعة', 'Receive leave / permission for review')}</CanButton><p className="text-sm">{t('يرتبط عدم التوافر بمصدره وإصداره. يلزم اعتماد المراجعة قبل تأثيره على الحضور والتغطية.', 'Unavailability retains its source and version. Review approval is required before affecting attendance and coverage.')}</p><DataList rows={state.leaves} columns={[{ key: 'employeeId', label: ['الموظف', 'Employee'] }, { key: 'start', label: ['من', 'From'] }, { key: 'end', label: ['إلى', 'To'] }, { key: 'paid', label: ['مدفوعة', 'Paid'] }, { key: 'sourceId', label: ['مرجع المصدر', 'Source reference'] }, { key: 'version', label: ['الإصدار', 'Version'] }, { key: 'status', label: ['الحالة', 'Status'], render: l => <Status value={l.status} /> }]} actions={l => <><CanButton action="leave" entity={state.employments.find((e: Row) => e.employeeId === l.employeeId)} disabled={l.status !== 'pending'} onClick={() => decision('leave.approve', { id: l.id }, t('اعتماد أثر الإجازة', 'Approve leave impact'))}>{t('اعتماد', 'Approve')}</CanButton><CanButton action="leave" entity={state.employments.find((e: Row) => e.employeeId === l.employeeId)} disabled={l.status !== 'approved'} onClick={() => decision('leave.cancel', { id: l.id }, t('إلغاء الإجازة وإرسال حركة عكس', 'Cancel leave and send reversal'))}>{t('إلغاء', 'Cancel')}</CanButton></>} /></>}
  </Panel>
  {dialog?.kind === 'decision' && <Decision {...dialog} onClose={() => setDialog(null)} />}
  {dialog?.kind === 'punch' && <EditDialog title={t('بصمة مصدر جديدة', 'New raw event')} initial={{ kind: 'in', source: 'manual', sourceEventId: crypto.randomUUID() }} fields={[{ ...textField('employeeId', 'الموظف', 'Employee', 'select'), options: employeeOptions }, textField('at', 'وقت الحدث UTC', 'Event time UTC', 'datetime-local'), { ...textField('kind', 'النوع', 'Kind', 'select'), options: opts(['in', 'out']) }, textField('siteCode', 'رمز الموقع', 'Site code'), textField('source', 'المصدر', 'Source'), textField('sourceEventId', 'معرف الحدث في المصدر', 'Source event ID')]} onClose={() => setDialog(null)} onSave={(v, reason) => command('punch.ingest', { events: [{ ...v, at: utc(v.at) }] }, reason)} />}
  {dialog?.kind === 'correction' && <EditDialog title={t('تصحيح مستقل للبصمة', 'Separate punch correction')} initial={{ at: dialog.punch.at.slice(0, 16), kind: ['in', 'out'].includes(dialog.punch.kind) ? dialog.punch.kind : 'in', siteCode: dialog.punch.siteCode, exclude: false }} fields={[textField('at', 'الوقت المصحح UTC', 'Corrected time UTC', 'datetime-local'), { ...textField('kind', 'النوع', 'Kind', 'select'), options: opts(['in', 'out']) }, { ...textField('siteCode', 'الموقع الصحيح لتوثيق حدث غير معروف', 'Verified site for unidentified scans', 'select', false), options: state.sites.map((s: Row) => ({ value: s.code, label: s.nameAr })) }, textField('exclude', 'استبعاد من الحساب مع حفظ الخام', 'Exclude from calculation, retain raw event', 'checkbox', false), { ...textField('assignmentKey', 'حسم الربط بفترة منشورة', 'Resolve to published period', 'select', false), options: assignments.filter(a => a.employeeId === dialog.punch.employeeId).map(a => ({ value: a.key, label: `${a.workDate} · ${a.shift.code} · ${a.start}` })) }]} onClose={() => setDialog(null)} onSave={(v, reason) => command('correction.request', { punchId: dialog.punch.id, replacement: { at: utc(v.at), kind: v.kind, siteCode: v.siteCode }, exclude: v.exclude, assignmentKey: v.assignmentKey }, reason)} />}
  {dialog?.kind === 'overtime' && <EditDialog title={t('اعتماد دقائق إضافي مؤهلة', 'Approve eligible overtime minutes')} initial={{ minutes: 0 }} fields={[{ ...textField('minutes', 'الدقائق المعتمدة', 'Approved minutes', 'number'), max: dialog.result.eligibleOvertimeMinutes }]} onClose={() => setDialog(null)} onSave={(v, reason) => command('attendance.overtime', { id: dialog.result.id, minutes: v.minutes }, reason)} />}
  {dialog?.kind === 'leave' && <EditDialog title={t('إجازة أو إذن مؤرخ', 'Dated leave / permission')} initial={{ paid: false, source: 'leave-review', sourceVersion: 1 }} fields={[{ ...textField('employeeId', 'الموظف', 'Employee', 'select'), options: employeeOptions }, textField('start', 'بداية الإعفاء UTC', 'Exemption start UTC', 'datetime-local'), textField('end', 'نهاية الإعفاء UTC', 'Exemption end UTC', 'datetime-local'), textField('paid', 'مدفوعة', 'Paid', 'checkbox', false), textField('leaveType', 'نوع الإجازة', 'Leave type'), textField('source', 'المصدر', 'Source'), textField('sourceId', 'رقم الطلب الأصلي', 'Original request reference'), textField('sourceVersion', 'إصدار المصدر', 'Source version', 'number')]} onClose={() => setDialog(null)} onSave={(v, reason) => command('leave.save', { value: { ...v, start: utc(v.start), end: utc(v.end) } }, reason)} />}
  </div>;
}
export function Reports({ auditOnly = false }: { auditOnly?: boolean }) {
  const { state, audit, companyId, command, actor } = useM08(), t = useText();
  const [filters, setFilters] = useState<Row>({ from: new Date().toISOString().slice(0, 7) + '-01', to: new Date().toISOString().slice(0, 10), report: auditOnly ? 'audit' : 'rosters', branch: '', siteCode: '', status: '', employeeId: '' }), [dialog, setDialog] = useState<Row | null>(null), [error, setError] = useState(''), [success, setSuccess] = useState('');
  const matches = (r: Row) => (!filters.branch || r.branch === filters.branch) && (!filters.siteCode || r.siteCode === filters.siteCode) && (!filters.status || r.status === filters.status) && (!filters.employeeId || r.employeeId === filters.employeeId);
  let rows: Row[] = []; try { rows = reportRows(state, filters.report, filters.from, filters.to, audit).filter(matches); } catch { /* Invalid transient date is shown below. */ }
  return <div className="space-y-4"><Panel title={auditOnly ? t('سجل الإصدارات والتدقيق', 'Versions and audit') : t('تقارير الوقت والتغطية', 'Time and coverage reports')}>
    <Fields value={filters} onChange={v => { setFilters(v); setError(''); setSuccess(''); }} fields={[textField('from', 'من', 'From', 'date'), textField('to', 'إلى', 'To', 'date'), { ...textField('report', 'التقرير', 'Report', 'select'), options: REPORT_OPTIONS.filter(([key]) => auditOnly ? key === 'audit' : key !== 'cost_centers' || actor.grants.some((g: Row) => g.fields?.includes('cost'))).map(([key, ar, en]) => ({ value: key!, label: t(ar!, en!) })) }, { ...textField('branch', 'الفرع', 'Branch', 'select', false), options: opts([...new Set<string>(state.employments.map((e: Row) => String(e.branch)))]) }, { ...textField('siteCode', 'الموقع', 'Site', 'select', false), options: opts([...new Set<string>(state.sites.map((s: Row) => String(s.code)))]) }, { ...textField('status', 'حالة النسخة', 'Version status', 'select', false), options: opts(['draft', 'review', 'approved', 'published', 'superseded', 'accepted', 'pending', 'rejected']) }, { ...textField('employeeId', 'الموظف', 'Employee', 'select', false), options: state.employments.map((e: Row) => ({ value: e.employeeId, label: `${e.code} · ${e.nameAr}` })) }]} />
    {filters.to < filters.from && <p role="alert">{t('نهاية الفترة قبل بدايتها', 'End precedes start')}</p>}
    <CanButton action="export" disabled={filters.to < filters.from} onClick={() => {
      setError(''); setSuccess(''); void authHeaders().then(headers => exportM08({ data: { companyId, from: filters.from, to: filters.to, report: filters.report, branch: filters.branch || undefined, siteCode: filters.siteCode || undefined }, headers })).then(output => {
        const content = csvExport(output.rows.filter(matches), { generatedAt: output.generatedAt, companyId, from: filters.from, to: filters.to, revision: output.revision, branch: filters.branch, siteCode: filters.siteCode, status: filters.status, employeeId: filters.employeeId });
        const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type: 'text/csv;charset=utf-8' })); link.download = `M08_${filters.report}_${filters.from}.csv`; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 30000);
        setSuccess(t('تم تجهيز وتصدير النتائج المصرح بها.', 'Authorized report exported.'));
      }).catch(e => setError(e.message));
    }}>{t('تصدير CSV بصلاحية الخادم', 'Export CSV')}</CanButton>{error && <p role="alert" className="text-red-700">{error}</p>}{success && <p role="status" className="text-teal-700">{success}</p>}
    {auditOnly && <p className="text-xs text-muted-foreground">{t('يعرض آخر 200 عملية متاحة ضمن الصلاحية. الإصدارات السابقة محفوظة في قاعدة البيانات.', 'Shows the latest 200 authorized operations. Older versions remain stored in the database.')}</p>}
    <DataList rows={rows} columns={[...new Set<string>(rows.flatMap(r => Object.keys(r)))].map(key => ({ key, label: REPORT_COLUMNS[key] ?? [key, key] }))} />
  </Panel>
  {!auditOnly && <Panel title={t('تسليم الحضور المعتمد للرواتب', 'Approved attendance delivery to payroll')}><p className="text-sm">{t('السجل يسلّم كميات دقائق قابلة للتتبع. قبول النظام المستلم ورقم مرجعه مطلوبان؛ حساب المبالغ والقيد المالي خارج هذه الوحدة.', 'This ledger delivers traceable minute quantities. A receiver acknowledgment and reference are required; monetary calculations and financial posting belong to payroll.')}</p>
    <CanButton action="payroll_close" onClick={() => setDialog({ kind: 'period' })}>{t('إنشاء دورة رواتب', 'Create payroll period')}</CanButton>
    <DataList rows={state.payrollPeriods} columns={[{ key: 'id', label: ['الدورة', 'Period'] }, { key: 'from', label: ['من', 'From'] }, { key: 'to', label: ['إلى', 'To'] }, { key: 'status', label: ['الحالة', 'Status'], render: p => <Status value={p.status} /> }]} actions={p => <CanButton action="payroll_close" disabled={p.status === 'closed'} onClick={() => setDialog({ kind: 'decision', title: t('إقفال دورة الرواتب', 'Close payroll period'), action: 'payroll.period', payload: { ...p, status: 'closed' } })}>{t('إقفال', 'Close')}</CanButton>} />
    <DataList rows={state.results.filter((r: Row) => r.approval.status === 'approved')} columns={[{ key: 'id', label: ['نتيجة الحضور', 'Attendance result'] }, { key: 'employeeId', label: ['الموظف', 'Employee'] }, { key: 'workDate', label: ['اليوم', 'Day'] }, { key: 'version', label: ['الإصدار', 'Version'] }, { key: 'paidMinutes', label: ['دقائق مدفوعة', 'Paid minutes'] }]} actions={r => <CanButton action="payroll" entity={state.employments.find((e: Row) => e.employeeId === r.employeeId)} onClick={() => setDialog({ kind: 'deliver', result: r })}>{t('تسليم أو تسوية الفرق', 'Deliver / adjust delta')}</CanButton>} />
    <DataList rows={state.deliveries} columns={[{ key: 'id', label: ['معرف التسليم', 'Delivery ID'] }, { key: 'kind', label: ['النوع', 'Kind'] }, { key: 'quantities', label: ['الكميات', 'Quantities'] }, { key: 'adjustmentOf', label: ['مرتبط بالأصل', 'Adjustment references'] }, { key: 'status', label: ['الحالة', 'Status'], render: d => <Status value={d.status} /> }, { key: 'externalReference', label: ['مرجع المستلم', 'Receiver reference'] }]} actions={d => <CanButton action={d.kind === 'payroll' ? 'payroll' : 'leave'} entity={state.employments.find((e: Row) => e.employeeId === d.employeeId)} disabled={!['pending', 'sent'].includes(d.status)} onClick={() => setDialog({ kind: 'respond', delivery: d })}>{t('تسجيل رد المستلم', 'Record receiver response')}</CanButton>} />
  </Panel>}
  {auditOnly && <Panel title={t('الإشعارات والتسليم', 'Notifications and delivery')}><DataList rows={state.notifications} columns={[{ key: 'kind', label: ['الحدث', 'Event'] }, { key: 'employeeId', label: ['الموظف', 'Employee'] }, { key: 'at', label: ['الوقت', 'Time'] }, { key: 'status', label: ['حالة التسليم', 'Delivery state'], render: n => <Status value={n.status} /> }, { key: 'attempts', label: ['المحاولات', 'Attempts'] }]} actions={n => <><CanButton action="notify" entity={state.employments.find((e: Row) => e.employeeId === n.employeeId)} disabled={n.status !== 'failed'} onClick={() => setDialog({ kind: 'decision', title: t('إعادة إرسال الإشعار فقط', 'Retry notification delivery'), action: 'notification.retry', payload: { id: n.id } })}>{t('إعادة المحاولة', 'Retry')}</CanButton><CanButton action="notify" entity={state.employments.find((e: Row) => e.employeeId === n.employeeId)} disabled={n.status === 'delivered'} onClick={() => setDialog({ kind: 'notify', notification: n })}>{t('حالة التسليم', 'Delivery status')}</CanButton>{n.userId === actor.id && !n.readAt && <Button onClick={() => { void command('notification.read', { id: n.id }, 'قراءة الإشعار / Notification read'); }}>{t('تمت القراءة', 'Mark read')}</Button>}</>} /></Panel>}
  {dialog?.kind === 'decision' && <Decision {...dialog} onClose={() => setDialog(null)} />}
  {dialog?.kind === 'period' && <EditDialog title={t('دورة رواتب جديدة', 'New payroll period')} initial={{ status: 'open' }} fields={[textField('from', 'من', 'From', 'date'), textField('to', 'إلى', 'To', 'date')]} onClose={() => setDialog(null)} onSave={(v, reason) => command('payroll.period', { ...v, status: 'open' }, reason)} />}
  {dialog?.kind === 'deliver' && <EditDialog title={t('تسليم إلى دورة مفتوحة', 'Deliver into an open period')} initial={{}} fields={[{ ...textField('periodId', 'الدورة المستلمة', 'Receiving period', 'select'), options: state.payrollPeriods.filter((p: Row) => p.status === 'open').map((p: Row) => ({ value: p.id, label: `${p.from} → ${p.to}` })) }]} onClose={() => setDialog(null)} onSave={(v, reason) => command('payroll.deliver', { resultId: dialog.result.id, periodId: v.periodId }, reason)} />}
  {dialog?.kind === 'respond' && <EditDialog title={t('رد النظام المستلم', 'Receiver response')} initial={{ status: 'accepted' }} fields={[{ ...textField('status', 'القرار', 'Decision', 'select'), options: opts(['accepted', 'rejected']) }, textField('externalReference', 'مرجع تأكيد النظام المستلم', 'Receiver confirmation reference')]} onClose={() => setDialog(null)} onSave={(v, reason) => command('delivery.respond', { id: dialog.delivery.id, ...v }, reason)} />}
  {dialog?.kind === 'notify' && <EditDialog title={t('تسجيل نتيجة إرسال القناة', 'Record channel delivery result')} initial={{ status: 'failed' }} fields={[{ ...textField('status', 'نتيجة القناة', 'Channel result', 'select'), options: opts(['delivered', 'failed']) }]} onClose={() => setDialog(null)} onSave={(v, reason) => command('notification.respond', { id: dialog.notification.id, ...v }, reason)} />}
  </div>;
}
