/* eslint-disable @typescript-eslint/no-explicit-any */
import { useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { previewM08Import } from '@/lib/m08/functions';
import { addDays, dates, localParts } from '@/lib/m08/time.mjs';
import { coverage, differences, IMPORT_COLUMNS, latest, publishedAssignments, validateRoster } from '@/lib/m08/planning.mjs';
import { Button, CanButton, DataList, Decision, EditDialog, Empty, Fields, Panel, Status, useM08, useText } from './common';
import { opts, parseRef, refs, textField, type Row, type Field } from './forms';
import { authHeaders } from './Definitions';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';

export function useSelectedRoster(publishedOnly = false) {
  const { state } = useM08(); const [id, setId] = useState(''); const list = state.rosters.filter((r: Row) => !publishedOnly || r.status === 'published');
  const roster = list.find((r: Row) => r.id === id) ?? list.at(-1) ?? null;
  return { roster, list, setId };
}
export function RosterPicker({ list, roster, onChange }: { list: Row[]; roster: Row; onChange: (id: string) => void }) {
  const t = useText(); return <label className="text-sm font-bold">{t('الجدول والإصدار', 'Roster and version')}<select value={roster?.id ?? ''} onChange={e => onChange(e.target.value)} className="ms-2 max-w-full rounded-lg border bg-card px-3 py-2"><option value="">{t('اختر جدولًا', 'Select roster')}</option>{list.map(r => <option key={r.id} value={r.id}>{r.name} · v{r.version} · {r.status} · {r.from} → {r.to}</option>)}</select></label>;
}
export function Rosters({ mine = false, approvals = false }: { mine?: boolean; approvals?: boolean }) {
  const { state, actor, command, lang } = useM08(), t = useText(); const { roster, list, setId } = useSelectedRoster(mine);
  const [dialog, setDialog] = useState<Row | null>(null), [selection, setSelection] = useState<string[]>([]), [mode, setMode] = useState('week'), [anchor, setAnchor] = useState(''), [page, setPage] = useState(0), [filters, setFilters] = useState<Row>({}), [dragged, setDragged] = useState<Row | null>(null);
  const editable = roster && ['draft', 'returned'].includes(roster.status), activeAnchor = anchor || roster?.from || new Date().toISOString().slice(0, 10);
  const days = useMemo(() => { const first = mode === 'month' ? activeAnchor.slice(0, 7) + '-01' : activeAnchor; const end = mode === 'month' ? new Date(Date.UTC(Number(first.slice(0, 4)), Number(first.slice(5, 7)), 0)).toISOString().slice(0, 10) : addDays(first, mode === 'day' ? 0 : 6); return dates(first, end); }, [activeAnchor, mode]);
  const source: Row[] = mine ? publishedAssignments(state) : roster?.assignments ?? [];
  const dayStatus = (employeeId: string, day: string) => {
    const rows = source.filter(a => a.employeeId === employeeId && a.workDate === day);
    const leave = state.leaves.some((l: Row) => l.employeeId === employeeId && l.status === 'approved' && rows.some(a => a.start && Date.parse(l.start) < Date.parse(a.end) && Date.parse(l.end) > Date.parse(a.start)));
    return leave ? 'LEAVE' : rows[0]?.dayType || 'UNSCHEDULED';
  };
  const employees: Row[] = [...new Set(state.employments.map((e: Row) => e.id))].map(id => latest(state.employments, String(id))).filter(e => (!mine || e.userId === actor.id) && (!roster || roster.employeeIds.includes(e.employeeId)) && ['branch', 'department', 'team', 'job', 'employeeId'].every(key => !filters[key] || e[key] === filters[key]) && (!filters.skill || e.skills.some((s: Row) => (typeof s === 'string' ? s : s.code) === filters.skill)) && (!filters.siteCode || e.siteCode === filters.siteCode || source.some(a => a.employeeId === e.employeeId && days.includes(a.workDate) && a.siteCode === filters.siteCode)) && (!filters.status || days.some(day => dayStatus(e.employeeId, day) === filters.status)));
  const selectedAssignments = source.filter(a => employees.some(e => e.employeeId === a.employeeId) && days.includes(a.workDate) && (!filters.status || dayStatus(a.employeeId, a.workDate) === filters.status));
  const totals = { minutes: selectedAssignments.reduce((n, a) => n + (a.shift?.requiredMinutes ?? 0), 0), nights: selectedAssignments.filter(a => a.shift?.endDay === 1).length, rest: selectedAssignments.filter(a => a.dayType === 'OFF').length,
    unscheduled: employees.length * days.length - new Set(selectedAssignments.map(a => `${a.employeeId}:${a.workDate}`)).size };
  const currentCoverage = coverage(state, source, state.demands.filter((d: Row) => days.includes(d.workDate)));
  const issues = roster && !mine ? validateRoster(state, roster) : [];
  const action = (name: string, title: string) => setDialog({ kind: 'decision', action: `roster.${name}`, title, payload: { rosterId: roster.id, version: roster.version } });
  const employeeOptions = state.employments.map((e: Row) => ({ value: e.employeeId, label: `${e.code} · ${lang ? e.nameEn : e.nameAr}` }));
  const createFields: Field[] = [textField('name', 'اسم الجدول', 'Roster name'), textField('from', 'من', 'From', 'date'), textField('to', 'إلى', 'To', 'date'), { ...textField('employeeIds', 'الموظفون', 'Employees', 'multi'), options: employeeOptions }, { ...textField('policyRef', 'السياسة المعتمدة', 'Approved policy', 'select'), options: refs(state.policies, lang) }];
  return <div className="space-y-4">
    <Panel title={mine ? t('دوامي المنشور', 'My published schedule') : t('إعداد الجدول ومراجعة النسخ', 'Plan and review rosters')}>
      <div className="flex flex-wrap items-center gap-3"><RosterPicker list={list} roster={roster} onChange={id => { setId(id); setAnchor(''); setSelection([]); }} />{!mine && <CanButton action="draft" icon="add" primary onClick={() => setDialog({ kind: 'create' })}>{t('جدول جديد', 'New roster')}</CanButton>}</div>
      {!mine && roster && <div className="flex flex-wrap gap-2">
        <CanButton action="draft" disabled={!editable} onClick={() => setDialog({ kind: 'assign' })}>{t('إسناد المحدد', 'Assign selected')}</CanButton>
        <CanButton action="draft" disabled={!editable} onClick={() => setDialog({ kind: 'generate' })}>{t('توليد من الأنماط', 'Generate from patterns')}</CanButton>
        <CanButton action="draft" disabled={!editable} onClick={() => setDialog({ kind: 'copy' })}>{t('نسخ أو تكرار فترة', 'Copy / repeat period')}</CanButton>
        <CanButton action="draft" disabled={!editable || !roster.history.length} onClick={() => action('undo', t('التراجع عن آخر تعديل', 'Undo last edit'))}>{t('تراجع', 'Undo')}</CanButton>
        <CanButton action="draft" onClick={() => action('validate', t('فحص التعارضات', 'Validate conflicts'))}>{t('فحص', 'Validate')}</CanButton>
        <CanButton action="draft" disabled={!editable} onClick={() => action('submit', t('إرسال النسخة للاعتماد', 'Submit this version'))}>{t('إرسال للاعتماد', 'Submit')}</CanButton>
        <CanButton action="approve" disabled={roster.status !== 'review'} onClick={() => action('approve', t('اعتماد هذه المرحلة', 'Approve this stage'))}>{t('اعتماد', 'Approve')}</CanButton>
        <CanButton action="approve" disabled={!['review', 'approved'].includes(roster.status)} onClick={() => action('return', t('إعادة للتعديل', 'Return for changes'))}>{t('إعادة', 'Return')}</CanButton>
        <CanButton action="publish" disabled={roster.status !== 'approved'} primary onClick={() => action('publish', t('نشر النسخة وإخطار المتأثرين', 'Publish and notify affected employees'))}>{t('نشر', 'Publish')}</CanButton>
        <CanButton action="revise" disabled={roster.status !== 'published'} onClick={() => action('revise', t('إنشاء نسخة تعديل مع الحفاظ على المنشور', 'Create a revision preserving the published roster'))}>{t('تعديل المنشور', 'Revise published')}</CanButton>
        <CanButton action="draft" disabled={!editable || !selection.length} onClick={() => setDialog({ kind: 'decision', title: t('حذف التسكين من المسودة', 'Remove draft assignments'), action: 'roster.remove', payload: { rosterId: roster.id, version: roster.version, keys: source.filter(a => selection.includes(`${a.employeeId}|${a.workDate}`)).map(a => a.key) } })}>{t('إزالة المحدد', 'Remove selected')}</CanButton>
      </div>}
      {roster && <p className="flex flex-wrap items-center gap-2 text-xs"><Status value={roster.status} /><span>{t('الإصدار', 'Version')} {roster.version} · {roster.approvals.length} {t('موافقة', 'approvals')}</span><span>{t('آخر نشر', 'Last published')}: {roster.publishedAt || '—'}</span></p>}
    </Panel>
    {!list.length ? <Empty text={mine ? t('لم يُنشر جدول لك بعد.', 'No schedule has been published for you yet.') : t('أنشئ جدولًا بعد إعداد السياسة وربط الموظفين.', 'Create a roster after configuring a policy and employee links.')} /> : <>
      <Panel title={t('العرض والفلاتر', 'View and filters')}><div className="flex flex-wrap gap-2">{['day', 'week', 'month'].map((m, i) => <Button key={m} primary={m === mode} onClick={() => setMode(m)}>{lang ? ['Day', 'Week', 'Month'][i] : ['يوم', 'أسبوع', 'شهر'][i]}</Button>)}<input aria-label={t('تاريخ العرض', 'View date')} type="date" value={activeAnchor} onChange={e => setAnchor(e.target.value)} className="rounded-lg border px-3" /></div>
        <Fields value={filters} onChange={v => { setFilters(v); setPage(0); }} fields={[
          ...[['branch', 'الفرع', 'Branch'], ['department', 'القسم', 'Department'], ['team', 'الفريق', 'Team'], ['job', 'الوظيفة', 'Job']].map(([key, ar, en]) => ({ ...textField(key!, ar!, en!, 'select', false), options: opts([...new Set<string>(state.employments.map((e: Row) => String(e[key!])))] ) })),
          { ...textField('siteCode', 'الموقع', 'Site', 'select', false), options: opts([...new Set<string>(state.sites.map((s: Row) => s.code))]) },
          { ...textField('skill', 'المهارة', 'Skill', 'select', false), options: opts([...new Set<string>(state.employments.flatMap((e: Row) => e.skills.map((s: Row) => typeof s === 'string' ? s : s.code)))]) },
          { ...textField('employeeId', 'الموظف', 'Employee', 'select', false), options: employeeOptions }, { ...textField('status', 'حالة اليوم', 'Day status', 'select', false), options: opts(['WORK', 'OFF', 'HOLIDAY', 'LEAVE', 'UNSCHEDULED']) },
        ]} />
      </Panel>
      <div className="grid grid-cols-2 gap-3 md:grid-cols-5">{[[t('ساعات مخططة', 'Planned hours'), (totals.minutes / 60).toFixed(2)], [t('شفتات ليلية', 'Night shifts'), totals.nights], [t('أيام راحة', 'Rest days'), totals.rest], [t('غير مجدول', 'Unscheduled'), totals.unscheduled], [t('التغطية', 'Coverage'), currentCoverage.ratio == null ? t('لا يوجد احتياج', 'No demand') : `${currentCoverage.ratio.toFixed(1)}%`]].map(([label, value]) => <div key={String(label)} className="rounded-xl border bg-card p-3"><p className="text-xs text-muted-foreground">{label}</p><strong className="mt-1 block text-xl text-primary">{value}</strong></div>)}</div>
      {!mine && editable && <div className="flex flex-wrap items-center gap-3"><Button onClick={() => setSelection(employees.flatMap(e => days.filter(d => d >= roster.from && d <= roster.to).map(d => `${e.employeeId}|${d}`)))}>{t('تحديد كل نتائج الفلتر في الفترة المعروضة', 'Select all filtered employees in displayed dates')}</Button><Button onClick={() => setSelection([])}>{t('مسح التحديد', 'Clear selection')}</Button><span className="text-sm">{selection.length} {t('خلية محددة', 'selected cells')}</span></div>}
      {!employees.length ? <Empty text={t('لا يوجد موظفون ضمن الفلاتر. راجع الربط أو غيّر الفلتر.', 'No employees match. Review bindings or adjust filters.')} /> : <div className="max-h-[65vh] overflow-auto rounded-xl border bg-card"><table className="border-separate border-spacing-0 text-sm"><thead className="sticky top-0 z-20 bg-secondary"><tr><th className="sticky start-0 z-30 min-w-48 border-e bg-secondary p-3 text-start">{t('الموظف', 'Employee')}</th>{days.map(day => <th key={day} className="min-w-40 border-e p-2"><time dateTime={day}>{new Intl.DateTimeFormat(lang ? 'en' : 'ar-EG', { weekday: 'short', day: 'numeric', month: 'short', timeZone: 'UTC' }).format(new Date(day))}</time></th>)}</tr></thead>
        <tbody>{employees.slice(page * 50, page * 50 + 50).map(e => <tr key={e.employeeId}><th className="sticky start-0 z-10 border-e border-t bg-card p-3 text-start"><span>{lang ? e.nameEn : e.nameAr}</span><small className="block font-normal text-muted-foreground">{e.code} · {e.team}</small></th>{days.map(day => {
          const rows = source.filter(a => a.employeeId === e.employeeId && a.workDate === day), status = dayStatus(e.employeeId, day), key = `${e.employeeId}|${day}`, problems = issues.filter((i: Row) => i.employeeId === e.employeeId && i.workDate === day);
          const base = state.rosters.find((r: Row) => r.id === roster?.baseId), changed = base && differences(base.assignments.filter((a: Row) => a.employeeId === e.employeeId && a.workDate === day), rows).length > 0;
          return <td key={day} className={`border-e border-t p-1 align-top ${filters.status && status !== filters.status ? 'opacity-20' : ''}`} onDragOver={event => { if (editable) event.preventDefault(); }} onDrop={event => { event.preventDefault(); if (editable && dragged) setDialog({ kind: 'copy', initial: { sourceRosterId: roster.id, sourceFrom: dragged.day, sourceTo: dragged.day, targetFrom: day, targetEmployeeId: e.employeeId, replace: true }, dragEmployee: dragged.employeeId }); }}>
            <button type="button" draggable={!mine && editable && rows.length > 0} onDragStart={() => setDragged({ employeeId: e.employeeId, day })} onClick={() => { if (!mine && editable) setSelection(s => s.includes(key) ? s.filter(x => x !== key) : [...s, key]); else setDialog({ kind: 'detail', rows, employee: e, day }); }} className={`min-h-28 w-full space-y-1 rounded-lg p-2 text-start focus-visible:outline-primary ${selection.includes(key) ? 'bg-blue-50 ring-2 ring-primary' : 'hover:bg-secondary/50'}`} aria-pressed={selection.includes(key)} aria-label={`${e.code} ${day} ${status}`}>
              <Status value={status} />{rows.map(a => <div key={a.key}><strong style={{ color: a.shift?.color }}>{a.shift?.code}</strong>{a.start && <span dir="ltr" className="block text-xs">{localParts(Date.parse(a.start), a.timezone).time}–{localParts(Date.parse(a.end), a.timezone).time} {a.shift.endDay ? t('اليوم التالي', 'next day') : ''}</span>}<small className="block text-muted-foreground">{a.siteCode}</small></div>)}{problems.length > 0 && <span className="block text-xs text-red-700">⚠ {problems.length} {t('تعارض', 'issues')}</span>}{changed && <span className="block text-xs text-blue-700">{t('تعديل غير منشور', 'Unpublished change')}</span>}
            </button>
          </td>;
        })}</tr>)}</tbody></table></div>}
      <div className="flex gap-2"><Button disabled={!page} onClick={() => setPage(page - 1)}>{t('السابق', 'Previous')}</Button><span className="p-2 text-sm">{employees.length} {t('موظف', 'employees')}</span><Button disabled={(page + 1) * 50 >= employees.length} onClick={() => setPage(page + 1)}>{t('التالي', 'Next')}</Button></div>
      {(approvals || issues.length > 0) && <Panel title={t('المراجعة قبل النشر', 'Publication review')}><DataList rows={issues} columns={[{ key: 'code', label: ['القاعدة', 'Rule'] }, { key: 'severity', label: ['الشدة', 'Severity'] }, { key: 'message', label: ['النتيجة', 'Result'] }]} /><DataList rows={roster.approvals} columns={[{ key: 'stage', label: ['المرحلة', 'Stage'] }, { key: 'role', label: ['دور المعتمد', 'Approver role'] }, { key: 'actor', label: ['المعتمد', 'Approver'] }, { key: 'at', label: ['الوقت', 'Time'] }, { key: 'version', label: ['الإصدار', 'Version'] }]} /></Panel>}
    </>}
    {dialog?.kind === 'decision' && <Decision title={dialog.title} action={dialog.action} payload={dialog.payload} onClose={() => setDialog(null)} />}
    {dialog?.kind === 'create' && <EditDialog title={t('جدول جديد', 'New roster')} initial={{ employeeIds: [], from: activeAnchor, to: addDays(activeAnchor, 6) }} fields={createFields} onClose={() => setDialog(null)} onSave={async (v, reason) => { const p = parseRef(v.policyRef); return command('roster.create', { ...v, policyId: p.id, policyVersion: p.version }, reason); }} />}
    {dialog?.kind === 'assign' && <EditDialog title={`${t('إسناد إلى', 'Assign to')} ${selection.length} ${t('خلية', 'cells')}`} initial={{ dayType: 'WORK', periodNo: 1, replaceDay: false, disambiguation: 'reject' }} fields={[
      { ...textField('dayType', 'نوع اليوم', 'Day type', 'select'), options: opts(['WORK', 'OFF', 'HOLIDAY']) }, { ...textField('shiftRef', 'الشفت للعمل', 'Shift for work', 'select', false), options: refs(state.shifts, lang) }, textField('periodNo', 'رقم الفترة', 'Period number', 'number'), { ...textField('siteCode', 'الموقع (اختياري لتوريث الموظف)', 'Site (optional employee default)', 'select', false), options: state.sites.map((s: Row) => ({ value: s.code, label: s.nameAr })) }, textField('costCenter', 'مركز التكلفة', 'Cost center', 'text', false), textField('replaceDay', 'استبدال اليوم كاملًا', 'Replace entire day', 'checkbox', false), { ...textField('disambiguation', 'معالجة الوقت المكرر', 'Repeated local time', 'select'), options: opts(['reject', 'earlier', 'later']) },
    ]} onClose={() => setDialog(null)} onSave={(v, reason) => { const p = parseRef(v.shiftRef); return command('roster.assign', { rosterId: roster.id, version: roster.version, cells: selection.map(key => { const [employeeId, workDate] = key.split('|'); return { ...v, employeeId, workDate, shiftId: p.id, shiftVersion: p.version }; }) }, reason); }} />}
    {dialog?.kind === 'generate' && <EditDialog title={t('توليد التسكين من الأنماط السارية', 'Generate from effective patterns')} initial={{ mode: 'fill' }} fields={[{ ...textField('mode', 'طريقة التطبيق', 'Apply mode', 'select'), options: opts(['fill', 'replace']) }]} onClose={() => setDialog(null)} onSave={(v, reason) => command('roster.generate', { rosterId: roster.id, version: roster.version, mode: v.mode }, reason)} />}
    {dialog?.kind === 'copy' && <EditDialog title={t('معاينة نطاق النسخ قبل إدخاله للمسودة', 'Review copy scope before applying to draft')} initial={dialog.initial ?? { sourceRosterId: roster.id, sourceFrom: roster.from, sourceTo: roster.to, targetFrom: activeAnchor, replace: false }} fields={[
      { ...textField('sourceRosterId', 'الجدول المصدر', 'Source roster', 'select'), options: list.map((r: Row) => ({ value: r.id, label: r.name })) }, textField('sourceFrom', 'بداية الفترة المصدر', 'Source from', 'date'), textField('sourceTo', 'نهاية الفترة المصدر', 'Source to', 'date'), textField('targetFrom', 'بداية الفترة الهدف', 'Target from', 'date'), { ...textField('targetEmployeeId', 'الموظف الهدف (اختياري)', 'Target employee (optional)', 'select', false), options: employeeOptions }, textField('replace', 'استبدال بيانات موجودة', 'Replace existing entries', 'checkbox', false),
    ]} onClose={() => setDialog(null)} onSave={(v, reason) => command('roster.copy', { ...v, rosterId: roster.id, version: roster.version, sourceEmployeeId: dialog.dragEmployee }, reason)} />}
    {dialog?.kind === 'detail' && <Dialog open onOpenChange={open => { if (!open) setDialog(null); }}><DialogContent dir={lang ? 'ltr' : 'rtl'} className="max-h-[90vh] max-w-5xl overflow-y-auto"><DialogTitle>{dialog.employee.code} · {dialog.day}</DialogTitle><DialogDescription>{t('تفاصيل اليوم ومصدر الإسناد والإصدارات المنشورة.', 'Day details, assignment source and published versions.')}</DialogDescription><DataList rows={dialog.rows} columns={[{ key: 'dayType', label: ['نوع اليوم', 'Day type'] }, { key: 'start', label: ['البداية', 'Start'] }, { key: 'end', label: ['النهاية', 'End'] }, { key: 'siteCode', label: ['الموقع', 'Site'] }, { key: 'source', label: ['المصدر', 'Source'] }, { key: 'shiftVersion', label: ['إصدار الشفت', 'Shift version'] }, { key: 'breaks', label: ['الاستراحات', 'Breaks'] }]} /><Button onClick={() => setDialog(null)}>{t('إغلاق', 'Close')}</Button></DialogContent></Dialog>}
  </div>;
}
export function ImportRoster() {
  const { state, companyId, command } = useM08(), t = useText(); const { roster, list, setId } = useSelectedRoster();
  const [rows, setRows] = useState<Row[]>([]), [preview, setPreview] = useState<Row | null>(null), [error, setError] = useState(''), [reading, setReading] = useState(false), [reason, setReason] = useState('');
  const editable = roster && ['draft', 'returned'].includes(roster.status);
  return <Panel title={t('استيراد إلى مسودة فقط', 'Import into a draft')}><RosterPicker list={list} roster={roster} onChange={id => { setId(id); setPreview(null); }} /><p className="text-sm">{t('كل صف يمثل فترة. اجعل أرقام الموظفين نصوصًا للحفاظ على الأصفار. تُرفض الدفعة كاملة إذا احتوت أخطاء.', 'One period per row. Store employee codes as text to preserve zeros. The entire batch is rejected if errors remain.')}</p>
    <Button onClick={() => { const ws = XLSX.utils.aoa_to_sheet([IMPORT_COLUMNS]); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, 'Roster'); XLSX.writeFile(wb, 'M08_Roster_Import.xlsx'); }}>{t('تنزيل قالب Excel', 'Download Excel template')}</Button>
    <input aria-label={t('ملف الاستيراد', 'Import file')} type="file" accept=".xlsx,.csv" disabled={!editable || reading} onChange={async e => {
      const file = e.target.files?.[0]; if (!file) return; setReading(true); setError(''); setPreview(null);
      try {
        if (file.size > 10 * 1024 * 1024) throw new Error(t('الملف أكبر من 10 ميجابايت', 'File exceeds 10 MB'));
        const wb = XLSX.read(await file.arrayBuffer(), { type: 'array', raw: true, cellText: true, cellDates: false }); const sheet = wb.Sheets[wb.SheetNames[0]!]; if (!sheet) throw new Error('Empty workbook');
        const matrix = XLSX.utils.sheet_to_json<string[]>(sheet, { header: 1, raw: false, defval: '' }); const header = matrix.shift() ?? [];
        if (IMPORT_COLUMNS.some(c => !header.includes(c)) || new Set(header).size !== header.length) throw new Error(t('أعمدة القالب ناقصة أو مكررة', 'Missing or duplicate headers'));
        const data = matrix.filter(row => row.some(v => v !== '')).map(row => Object.fromEntries(header.map((key, i) => [key, String(row[i] ?? '')])));
        if (data.length > 10000) throw new Error(t('الحد 10000 صف', 'Maximum 10,000 rows')); setRows(data);
        const result = await previewM08Import({ data: { companyId, rosterId: roster.id, rows: data }, headers: await authHeaders() }); setPreview(result);
      } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setReading(false); }
    }} />
    {reading && <p role="status">{t('جاري قراءة الملف وفحص الدفعة…', 'Reading and validating batch…')}</p>}{error && <p role="alert" className="text-red-700">{error}</p>}
    {preview && <><p role="status">{preview.inputCount} {t('صف — أخطاء', 'rows — errors')}: {preview.errors.length}</p><DataList rows={preview.errors} columns={[{ key: 'row', label: ['الصف', 'Row'] }, { key: 'column', label: ['العمود', 'Column'] }, { key: 'employeeCode', label: ['الموظف', 'Employee'] }, { key: 'workDate', label: ['التاريخ', 'Date'] }, { key: 'message', label: ['الخطأ', 'Error'] }]} /><DataList rows={rows} columns={IMPORT_COLUMNS.map(key => ({ key, label: [key, key] }))} /><label className="block text-sm">{t('سبب الاستيراد', 'Import reason')}<input value={reason} onChange={e => setReason(e.target.value)} className="ms-2 rounded-lg border p-2" /></label><CanButton action="import" disabled={preview.errors.length > 0 || !editable || reason.trim().length < 3} primary onClick={() => { void command('roster.import', { rosterId: roster.id, version: roster.version, rows }, reason).then(ok => { if (ok) { setRows([]); setPreview(null); } }); }}>{t('إدخال الدفعة إلى المسودة', 'Apply batch to draft')}</CanButton></>}
  </Panel>;
}
