/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalRequestsRouteImport } from './routes/approval-requests'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CorrespondenceRouteImport } from './routes/correspondence'
import { Route as EndOfServiceProvisionRouteImport } from './routes/end-of-service-provision'
import { Route as EndOfServiceRequestsRouteImport } from './routes/end-of-service-requests'
import { Route as InquiriesRouteImport } from './routes/inquiries'
import { Route as LeavesRouteImport } from './routes/leaves'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PermitsRouteImport } from './routes/permits'
import { Route as RegulationsRouteImport } from './routes/regulations'
import { Route as RequestNotificationsRouteImport } from './routes/request-notifications'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as VacationsRouteImport } from './routes/vacations'
import { Route as PayrollBankFileRouteImport } from './routes/payroll.bank-file'
import { Route as RegulationsIndexRouteImport } from './routes/regulations.index'
import { Route as RegulationsApprovalsRouteImport } from './routes/regulations.approvals'
import { Route as RegulationsBankFeesRouteImport } from './routes/regulations.bank-fees'
import { Route as RegulationsDeductionsRouteImport } from './routes/regulations.deductions'
import { Route as RegulationsEosRouteImport } from './routes/regulations.eos'
import { Route as RegulationsFingerprintRouteImport } from './routes/regulations.fingerprint'
import { Route as RegulationsLoansRouteImport } from './routes/regulations.loans'
import { Route as RegulationsOtherRouteImport } from './routes/regulations.other'
import { Route as RegulationsPermitsRouteImport } from './routes/regulations.permits'
import { Route as RegulationsShiftsRouteImport } from './routes/regulations.shifts'
import { Route as RegulationsVacationsRouteImport } from './routes/regulations.vacations'
import { Route as ReportsAbsenceDailyRouteImport } from './routes/reports.absence-daily'
import { Route as ReportsAbsenceDaysCountRouteImport } from './routes/reports.absence-days-count'
import { Route as ReportsAbsenceDaysListRouteImport } from './routes/reports.absence-days-list'
import { Route as ReportsAbsenceEmployeeRouteImport } from './routes/reports.absence-employee'
import { Route as ReportsAbsenceLateComparisonRouteImport } from './routes/reports.absence-late-comparison'
import { Route as ReportsAbsenceMonthlyRouteImport } from './routes/reports.absence-monthly'
import { Route as ReportsAbsenceValueRouteImport } from './routes/reports.absence-value'
import { Route as ReportsAdminFormsRouteImport } from './routes/reports.admin-forms'
import { Route as ReportsArchiveRouteImport } from './routes/reports.archive'
import { Route as ReportsAttendanceRouteImport } from './routes/reports.attendance'
import { Route as ReportsAttendanceComprehensiveRouteImport } from './routes/reports.attendance-comprehensive'
import { Route as ReportsAttendanceDetailedRouteImport } from './routes/reports.attendance-detailed'
import { Route as ReportsAttendanceStatisticsRouteImport } from './routes/reports.attendance-statistics'
import { Route as ReportsBankStatementRouteImport } from './routes/reports.bank-statement'
import { Route as ReportsBasicDataRouteImport } from './routes/reports.basic-data'
import { Route as ReportsDailyLateRouteImport } from './routes/reports.daily-late'
import { Route as ReportsEarlyCheckoutDaysRouteImport } from './routes/reports.early-checkout-days'
import { Route as ReportsEmployeeAccountStatementRouteImport } from './routes/reports.employee-account-statement'
import { Route as ReportsEmployeeCertificatesRouteImport } from './routes/reports.employee-certificates'
import { Route as ReportsEmployeeContractsReportRouteImport } from './routes/reports.employee-contracts-report'
import { Route as ReportsEmployeeDataRouteImport } from './routes/reports.employee-data'
import { Route as ReportsEmployeeDependentsRouteImport } from './routes/reports.employee-dependents'
import { Route as ReportsEmployeeFilesRouteImport } from './routes/reports.employee-files'
import { Route as ReportsEmployeeHeadcountRouteImport } from './routes/reports.employee-headcount'
import { Route as ReportsEmployeeLeavesRouteImport } from './routes/reports.employee-leaves'
import { Route as ReportsEmployeeTrainingRouteImport } from './routes/reports.employee-training'
import { Route as ReportsEntitlementsDeductionsRouteImport } from './routes/reports.entitlements-deductions'
import { Route as ReportsEvaluationRouteImport } from './routes/reports.evaluation'
import { Route as ReportsExceptionsRouteImport } from './routes/reports.exceptions'
import { Route as ReportsFinancialDataRouteImport } from './routes/reports.financial-data'
import { Route as ReportsFingerprintRouteImport } from './routes/reports.fingerprint'
import { Route as ReportsHireAndTerminationRouteImport } from './routes/reports.hire-and-termination'
import { Route as ReportsHistoricalLeavesRouteImport } from './routes/reports.historical-leaves'
import { Route as ReportsLateDaysListRouteImport } from './routes/reports.late-days-list'
import { Route as ReportsLateMinutesRouteImport } from './routes/reports.late-minutes'
import { Route as ReportsLoansBalanceRouteImport } from './routes/reports.loans-balance'
import { Route as ReportsLoansDataRouteImport } from './routes/reports.loans-data'
import { Route as ReportsManpowerBudgetRouteImport } from './routes/reports.manpower-budget'
import { Route as ReportsMedicalInsuranceRouteImport } from './routes/reports.medical-insurance'
import { Route as ReportsPayrollAdjustmentsRouteImport } from './routes/reports.payroll-adjustments'
import { Route as ReportsPayrollComparisonRouteImport } from './routes/reports.payroll-comparison'
import { Route as ReportsPayrollSheetRouteImport } from './routes/reports.payroll-sheet'
import { Route as ReportsPettyCashRouteImport } from './routes/reports.petty-cash'
import { Route as ReportsRequestsSummaryRouteImport } from './routes/reports.requests-summary'
import { Route as ReportsSurveysReportRouteImport } from './routes/reports.surveys-report'
import { Route as RequestsPurchaseBudgetRouteImport } from './routes/requests.purchase-budget'
import { Route as RequestsSetupRouteImport } from './routes/requests.setup'
import { Route as SettingsAccountLinksRouteImport } from './routes/settings.account-links'
import { Route as SettingsBasicRouteImport } from './routes/settings.basic'
import { Route as SettingsBranchQuotasRouteImport } from './routes/settings.branch-quotas'
import { Route as SettingsBranchesRouteImport } from './routes/settings.branches'
import { Route as SettingsCalendarRouteImport } from './routes/settings.calendar'
import { Route as SettingsCompanyRouteImport } from './routes/settings.company'
import { Route as SettingsCompanyDocumentsRouteImport } from './routes/settings.company-documents'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsSponsorsRouteImport } from './routes/settings.sponsors'
import { Route as SettingsSuspensionReasonsRouteImport } from './routes/settings.suspension-reasons'
import { Route as ShiftsApprovalsRouteImport } from './routes/shifts.approvals'
import { Route as ShiftsAuditRouteImport } from './routes/shifts.audit'
import { Route as ShiftsBindingsRouteImport } from './routes/shifts.bindings'
import { Route as ShiftsCoverageRouteImport } from './routes/shifts.coverage'
import { Route as ShiftsExceptionsRouteImport } from './routes/shifts.exceptions'
import { Route as ShiftsImportRouteImport } from './routes/shifts.import'
import { Route as ShiftsLibraryRouteImport } from './routes/shifts.library'
import { Route as ShiftsMineRouteImport } from './routes/shifts.mine'
import { Route as ShiftsOpenRouteImport } from './routes/shifts.open'
import { Route as ShiftsPatternsRouteImport } from './routes/shifts.patterns'
import { Route as ShiftsPoliciesRouteImport } from './routes/shifts.policies'
import { Route as ShiftsReportsRouteImport } from './routes/shifts.reports'
import { Route as ShiftsRequestsRouteImport } from './routes/shifts.requests'
import { Route as ShiftsRostersRouteImport } from './routes/shifts.rosters'
import { Route as ShiftsTemplatesRouteImport } from './routes/shifts.templates'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffAddRouteImport } from './routes/staff.add'
import { Route as StaffBankBlockRouteImport } from './routes/staff.bank-block'
import { Route as StaffContractsRouteImport } from './routes/staff.contracts'
import { Route as StaffManagerRouteImport } from './routes/staff.manager'
import { Route as StaffTransferRouteImport } from './routes/staff.transfer'
import { Route as StaffUpdateRouteImport } from './routes/staff.update'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksPermissionsRouteImport } from './routes/tasks.permissions'
import { Route as TasksReportsRouteImport } from './routes/tasks.reports'
import { Route as TasksSetupRouteImport } from './routes/tasks.setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalRequestsRoute = ApprovalRequestsRouteImport.update({
  id: '/approval-requests',
  path: '/approval-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrespondenceRoute = CorrespondenceRouteImport.update({
  id: '/correspondence',
  path: '/correspondence',
  getParentRoute: () => rootRouteImport,
} as any)
const EndOfServiceProvisionRoute = EndOfServiceProvisionRouteImport.update({
  id: '/end-of-service-provision',
  path: '/end-of-service-provision',
  getParentRoute: () => rootRouteImport,
} as any)
const EndOfServiceRequestsRoute = EndOfServiceRequestsRouteImport.update({
  id: '/end-of-service-requests',
  path: '/end-of-service-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesRoute = InquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRoute = LeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PermitsRoute = PermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulationsRoute = RegulationsRouteImport.update({
  id: '/regulations',
  path: '/regulations',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestNotificationsRoute = RequestNotificationsRouteImport.update({
  id: '/request-notifications',
  path: '/request-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const VacationsRoute = VacationsRouteImport.update({
  id: '/vacations',
  path: '/vacations',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollBankFileRoute = PayrollBankFileRouteImport.update({
  id: '/bank-file',
  path: '/bank-file',
  getParentRoute: () => PayrollRoute,
} as any)
const RegulationsIndexRoute = RegulationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsApprovalsRoute = RegulationsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsBankFeesRoute = RegulationsBankFeesRouteImport.update({
  id: '/bank-fees',
  path: '/bank-fees',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsDeductionsRoute = RegulationsDeductionsRouteImport.update({
  id: '/deductions',
  path: '/deductions',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsEosRoute = RegulationsEosRouteImport.update({
  id: '/eos',
  path: '/eos',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsFingerprintRoute = RegulationsFingerprintRouteImport.update({
  id: '/fingerprint',
  path: '/fingerprint',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsLoansRoute = RegulationsLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsOtherRoute = RegulationsOtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsPermitsRoute = RegulationsPermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsShiftsRoute = RegulationsShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsVacationsRoute = RegulationsVacationsRouteImport.update({
  id: '/vacations',
  path: '/vacations',
  getParentRoute: () => RegulationsRoute,
} as any)
const ReportsAbsenceDailyRoute = ReportsAbsenceDailyRouteImport.update({
  id: '/reports/absence-daily',
  path: '/reports/absence-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAbsenceDaysCountRoute = ReportsAbsenceDaysCountRouteImport.update({
  id: '/reports/absence-days-count',
  path: '/reports/absence-days-count',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAbsenceDaysListRoute = ReportsAbsenceDaysListRouteImport.update({
  id: '/reports/absence-days-list',
  path: '/reports/absence-days-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAbsenceEmployeeRoute = ReportsAbsenceEmployeeRouteImport.update({
  id: '/reports/absence-employee',
  path: '/reports/absence-employee',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAbsenceLateComparisonRoute =
  ReportsAbsenceLateComparisonRouteImport.update({
    id: '/reports/absence-late-comparison',
    path: '/reports/absence-late-comparison',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsAbsenceMonthlyRoute = ReportsAbsenceMonthlyRouteImport.update({
  id: '/reports/absence-monthly',
  path: '/reports/absence-monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAbsenceValueRoute = ReportsAbsenceValueRouteImport.update({
  id: '/reports/absence-value',
  path: '/reports/absence-value',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAdminFormsRoute = ReportsAdminFormsRouteImport.update({
  id: '/reports/admin-forms',
  path: '/reports/admin-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsArchiveRoute = ReportsArchiveRouteImport.update({
  id: '/reports/archive',
  path: '/reports/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAttendanceRoute = ReportsAttendanceRouteImport.update({
  id: '/reports/attendance',
  path: '/reports/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAttendanceComprehensiveRoute =
  ReportsAttendanceComprehensiveRouteImport.update({
    id: '/reports/attendance-comprehensive',
    path: '/reports/attendance-comprehensive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsAttendanceDetailedRoute =
  ReportsAttendanceDetailedRouteImport.update({
    id: '/reports/attendance-detailed',
    path: '/reports/attendance-detailed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsAttendanceStatisticsRoute =
  ReportsAttendanceStatisticsRouteImport.update({
    id: '/reports/attendance-statistics',
    path: '/reports/attendance-statistics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsBankStatementRoute = ReportsBankStatementRouteImport.update({
  id: '/reports/bank-statement',
  path: '/reports/bank-statement',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsBasicDataRoute = ReportsBasicDataRouteImport.update({
  id: '/reports/basic-data',
  path: '/reports/basic-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsDailyLateRoute = ReportsDailyLateRouteImport.update({
  id: '/reports/daily-late',
  path: '/reports/daily-late',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsEarlyCheckoutDaysRoute =
  ReportsEarlyCheckoutDaysRouteImport.update({
    id: '/reports/early-checkout-days',
    path: '/reports/early-checkout-days',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsEmployeeAccountStatementRoute =
  ReportsEmployeeAccountStatementRouteImport.update({
    id: '/reports/employee-account-statement',
    path: '/reports/employee-account-statement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsEmployeeCertificatesRoute =
  ReportsEmployeeCertificatesRouteImport.update({
    id: '/reports/employee-certificates',
    path: '/reports/employee-certificates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsEmployeeContractsReportRoute =
  ReportsEmployeeContractsReportRouteImport.update({
    id: '/reports/employee-contracts-report',
    path: '/reports/employee-contracts-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsEmployeeDataRoute = ReportsEmployeeDataRouteImport.update({
  id: '/reports/employee-data',
  path: '/reports/employee-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsEmployeeDependentsRoute =
  ReportsEmployeeDependentsRouteImport.update({
    id: '/reports/employee-dependents',
    path: '/reports/employee-dependents',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsEmployeeFilesRoute = ReportsEmployeeFilesRouteImport.update({
  id: '/reports/employee-files',
  path: '/reports/employee-files',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsEmployeeHeadcountRoute =
  ReportsEmployeeHeadcountRouteImport.update({
    id: '/reports/employee-headcount',
    path: '/reports/employee-headcount',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsEmployeeLeavesRoute = ReportsEmployeeLeavesRouteImport.update({
  id: '/reports/employee-leaves',
  path: '/reports/employee-leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsEmployeeTrainingRoute = ReportsEmployeeTrainingRouteImport.update({
  id: '/reports/employee-training',
  path: '/reports/employee-training',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsEntitlementsDeductionsRoute =
  ReportsEntitlementsDeductionsRouteImport.update({
    id: '/reports/entitlements-deductions',
    path: '/reports/entitlements-deductions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsEvaluationRoute = ReportsEvaluationRouteImport.update({
  id: '/reports/evaluation',
  path: '/reports/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsExceptionsRoute = ReportsExceptionsRouteImport.update({
  id: '/reports/exceptions',
  path: '/reports/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsFinancialDataRoute = ReportsFinancialDataRouteImport.update({
  id: '/reports/financial-data',
  path: '/reports/financial-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsFingerprintRoute = ReportsFingerprintRouteImport.update({
  id: '/reports/fingerprint',
  path: '/reports/fingerprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsHireAndTerminationRoute =
  ReportsHireAndTerminationRouteImport.update({
    id: '/reports/hire-and-termination',
    path: '/reports/hire-and-termination',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsHistoricalLeavesRoute = ReportsHistoricalLeavesRouteImport.update({
  id: '/reports/historical-leaves',
  path: '/reports/historical-leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsLateDaysListRoute = ReportsLateDaysListRouteImport.update({
  id: '/reports/late-days-list',
  path: '/reports/late-days-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsLateMinutesRoute = ReportsLateMinutesRouteImport.update({
  id: '/reports/late-minutes',
  path: '/reports/late-minutes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsLoansBalanceRoute = ReportsLoansBalanceRouteImport.update({
  id: '/reports/loans-balance',
  path: '/reports/loans-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsLoansDataRoute = ReportsLoansDataRouteImport.update({
  id: '/reports/loans-data',
  path: '/reports/loans-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsManpowerBudgetRoute = ReportsManpowerBudgetRouteImport.update({
  id: '/reports/manpower-budget',
  path: '/reports/manpower-budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsMedicalInsuranceRoute = ReportsMedicalInsuranceRouteImport.update({
  id: '/reports/medical-insurance',
  path: '/reports/medical-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPayrollAdjustmentsRoute =
  ReportsPayrollAdjustmentsRouteImport.update({
    id: '/reports/payroll-adjustments',
    path: '/reports/payroll-adjustments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsPayrollComparisonRoute =
  ReportsPayrollComparisonRouteImport.update({
    id: '/reports/payroll-comparison',
    path: '/reports/payroll-comparison',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsPayrollSheetRoute = ReportsPayrollSheetRouteImport.update({
  id: '/reports/payroll-sheet',
  path: '/reports/payroll-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPettyCashRoute = ReportsPettyCashRouteImport.update({
  id: '/reports/petty-cash',
  path: '/reports/petty-cash',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRequestsSummaryRoute = ReportsRequestsSummaryRouteImport.update({
  id: '/reports/requests-summary',
  path: '/reports/requests-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSurveysReportRoute = ReportsSurveysReportRouteImport.update({
  id: '/reports/surveys-report',
  path: '/reports/surveys-report',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsPurchaseBudgetRoute = RequestsPurchaseBudgetRouteImport.update({
  id: '/requests/purchase-budget',
  path: '/requests/purchase-budget',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsSetupRoute = RequestsSetupRouteImport.update({
  id: '/requests/setup',
  path: '/requests/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountLinksRoute = SettingsAccountLinksRouteImport.update({
  id: '/account-links',
  path: '/account-links',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBasicRoute = SettingsBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBranchQuotasRoute = SettingsBranchQuotasRouteImport.update({
  id: '/branch-quotas',
  path: '/branch-quotas',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBranchesRoute = SettingsBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCalendarRoute = SettingsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCompanyRoute = SettingsCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCompanyDocumentsRoute =
  SettingsCompanyDocumentsRouteImport.update({
    id: '/company-documents',
    path: '/company-documents',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSponsorsRoute = SettingsSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSuspensionReasonsRoute =
  SettingsSuspensionReasonsRouteImport.update({
    id: '/suspension-reasons',
    path: '/suspension-reasons',
    getParentRoute: () => SettingsRoute,
  } as any)
const ShiftsApprovalsRoute = ShiftsApprovalsRouteImport.update({
  id: '/shifts/approvals',
  path: '/shifts/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsAuditRoute = ShiftsAuditRouteImport.update({
  id: '/shifts/audit',
  path: '/shifts/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsBindingsRoute = ShiftsBindingsRouteImport.update({
  id: '/shifts/bindings',
  path: '/shifts/bindings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsCoverageRoute = ShiftsCoverageRouteImport.update({
  id: '/shifts/coverage',
  path: '/shifts/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsExceptionsRoute = ShiftsExceptionsRouteImport.update({
  id: '/shifts/exceptions',
  path: '/shifts/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsImportRoute = ShiftsImportRouteImport.update({
  id: '/shifts/import',
  path: '/shifts/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsLibraryRoute = ShiftsLibraryRouteImport.update({
  id: '/shifts/library',
  path: '/shifts/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsMineRoute = ShiftsMineRouteImport.update({
  id: '/shifts/mine',
  path: '/shifts/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsOpenRoute = ShiftsOpenRouteImport.update({
  id: '/shifts/open',
  path: '/shifts/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsPatternsRoute = ShiftsPatternsRouteImport.update({
  id: '/shifts/patterns',
  path: '/shifts/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsPoliciesRoute = ShiftsPoliciesRouteImport.update({
  id: '/shifts/policies',
  path: '/shifts/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsReportsRoute = ShiftsReportsRouteImport.update({
  id: '/shifts/reports',
  path: '/shifts/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRequestsRoute = ShiftsRequestsRouteImport.update({
  id: '/shifts/requests',
  path: '/shifts/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRostersRoute = ShiftsRostersRouteImport.update({
  id: '/shifts/rosters',
  path: '/shifts/rosters',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsTemplatesRoute = ShiftsTemplatesRouteImport.update({
  id: '/shifts/templates',
  path: '/shifts/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAddRoute = StaffAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBankBlockRoute = StaffBankBlockRouteImport.update({
  id: '/bank-block',
  path: '/bank-block',
  getParentRoute: () => StaffRoute,
} as any)
const StaffContractsRoute = StaffContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => StaffRoute,
} as any)
const StaffManagerRoute = StaffManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTransferRoute = StaffTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => StaffRoute,
} as any)
const StaffUpdateRoute = StaffUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => StaffRoute,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksPermissionsRoute = TasksPermissionsRouteImport.update({
  id: '/tasks/permissions',
  path: '/tasks/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksReportsRoute = TasksReportsRouteImport.update({
  id: '/tasks/reports',
  path: '/tasks/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSetupRoute = TasksSetupRouteImport.update({
  id: '/tasks/setup',
  path: '/tasks/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approval-requests': typeof ApprovalRequestsRoute
  '/auth': typeof AuthRoute
  '/correspondence': typeof CorrespondenceRoute
  '/end-of-service-provision': typeof EndOfServiceProvisionRoute
  '/end-of-service-requests': typeof EndOfServiceRequestsRoute
  '/inquiries': typeof InquiriesRoute
  '/leaves': typeof LeavesRoute
  '/loans': typeof LoansRoute
  '/payroll': typeof PayrollRouteWithChildren
  '/permissions': typeof PermissionsRoute
  '/permits': typeof PermitsRoute
  '/regulations': typeof RegulationsRouteWithChildren
  '/request-notifications': typeof RequestNotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/surveys': typeof SurveysRoute
  '/vacations': typeof VacationsRoute
  '/payroll/bank-file': typeof PayrollBankFileRoute
  '/regulations/approvals': typeof RegulationsApprovalsRoute
  '/regulations/bank-fees': typeof RegulationsBankFeesRoute
  '/regulations/deductions': typeof RegulationsDeductionsRoute
  '/regulations/eos': typeof RegulationsEosRoute
  '/regulations/fingerprint': typeof RegulationsFingerprintRoute
  '/regulations/loans': typeof RegulationsLoansRoute
  '/regulations/other': typeof RegulationsOtherRoute
  '/regulations/permits': typeof RegulationsPermitsRoute
  '/regulations/shifts': typeof RegulationsShiftsRoute
  '/regulations/vacations': typeof RegulationsVacationsRoute
  '/reports/absence-daily': typeof ReportsAbsenceDailyRoute
  '/reports/absence-days-count': typeof ReportsAbsenceDaysCountRoute
  '/reports/absence-days-list': typeof ReportsAbsenceDaysListRoute
  '/reports/absence-employee': typeof ReportsAbsenceEmployeeRoute
  '/reports/absence-late-comparison': typeof ReportsAbsenceLateComparisonRoute
  '/reports/absence-monthly': typeof ReportsAbsenceMonthlyRoute
  '/reports/absence-value': typeof ReportsAbsenceValueRoute
  '/reports/admin-forms': typeof ReportsAdminFormsRoute
  '/reports/archive': typeof ReportsArchiveRoute
  '/reports/attendance': typeof ReportsAttendanceRoute
  '/reports/attendance-comprehensive': typeof ReportsAttendanceComprehensiveRoute
  '/reports/attendance-detailed': typeof ReportsAttendanceDetailedRoute
  '/reports/attendance-statistics': typeof ReportsAttendanceStatisticsRoute
  '/reports/bank-statement': typeof ReportsBankStatementRoute
  '/reports/basic-data': typeof ReportsBasicDataRoute
  '/reports/daily-late': typeof ReportsDailyLateRoute
  '/reports/early-checkout-days': typeof ReportsEarlyCheckoutDaysRoute
  '/reports/employee-account-statement': typeof ReportsEmployeeAccountStatementRoute
  '/reports/employee-certificates': typeof ReportsEmployeeCertificatesRoute
  '/reports/employee-contracts-report': typeof ReportsEmployeeContractsReportRoute
  '/reports/employee-data': typeof ReportsEmployeeDataRoute
  '/reports/employee-dependents': typeof ReportsEmployeeDependentsRoute
  '/reports/employee-files': typeof ReportsEmployeeFilesRoute
  '/reports/employee-headcount': typeof ReportsEmployeeHeadcountRoute
  '/reports/employee-leaves': typeof ReportsEmployeeLeavesRoute
  '/reports/employee-training': typeof ReportsEmployeeTrainingRoute
  '/reports/entitlements-deductions': typeof ReportsEntitlementsDeductionsRoute
  '/reports/evaluation': typeof ReportsEvaluationRoute
  '/reports/exceptions': typeof ReportsExceptionsRoute
  '/reports/financial-data': typeof ReportsFinancialDataRoute
  '/reports/fingerprint': typeof ReportsFingerprintRoute
  '/reports/hire-and-termination': typeof ReportsHireAndTerminationRoute
  '/reports/historical-leaves': typeof ReportsHistoricalLeavesRoute
  '/reports/late-days-list': typeof ReportsLateDaysListRoute
  '/reports/late-minutes': typeof ReportsLateMinutesRoute
  '/reports/loans-balance': typeof ReportsLoansBalanceRoute
  '/reports/loans-data': typeof ReportsLoansDataRoute
  '/reports/manpower-budget': typeof ReportsManpowerBudgetRoute
  '/reports/medical-insurance': typeof ReportsMedicalInsuranceRoute
  '/reports/payroll-adjustments': typeof ReportsPayrollAdjustmentsRoute
  '/reports/payroll-comparison': typeof ReportsPayrollComparisonRoute
  '/reports/payroll-sheet': typeof ReportsPayrollSheetRoute
  '/reports/petty-cash': typeof ReportsPettyCashRoute
  '/reports/requests-summary': typeof ReportsRequestsSummaryRoute
  '/reports/surveys-report': typeof ReportsSurveysReportRoute
  '/requests/purchase-budget': typeof RequestsPurchaseBudgetRoute
  '/requests/setup': typeof RequestsSetupRoute
  '/settings/account-links': typeof SettingsAccountLinksRoute
  '/settings/basic': typeof SettingsBasicRoute
  '/settings/branch-quotas': typeof SettingsBranchQuotasRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/calendar': typeof SettingsCalendarRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/company-documents': typeof SettingsCompanyDocumentsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/sponsors': typeof SettingsSponsorsRoute
  '/settings/suspension-reasons': typeof SettingsSuspensionReasonsRoute
  '/shifts/approvals': typeof ShiftsApprovalsRoute
  '/shifts/audit': typeof ShiftsAuditRoute
  '/shifts/bindings': typeof ShiftsBindingsRoute
  '/shifts/coverage': typeof ShiftsCoverageRoute
  '/shifts/exceptions': typeof ShiftsExceptionsRoute
  '/shifts/import': typeof ShiftsImportRoute
  '/shifts/library': typeof ShiftsLibraryRoute
  '/shifts/mine': typeof ShiftsMineRoute
  '/shifts/open': typeof ShiftsOpenRoute
  '/shifts/patterns': typeof ShiftsPatternsRoute
  '/shifts/policies': typeof ShiftsPoliciesRoute
  '/shifts/reports': typeof ShiftsReportsRoute
  '/shifts/requests': typeof ShiftsRequestsRoute
  '/shifts/rosters': typeof ShiftsRostersRoute
  '/shifts/templates': typeof ShiftsTemplatesRoute
  '/staff/add': typeof StaffAddRoute
  '/staff/bank-block': typeof StaffBankBlockRoute
  '/staff/contracts': typeof StaffContractsRoute
  '/staff/manager': typeof StaffManagerRoute
  '/staff/transfer': typeof StaffTransferRoute
  '/staff/update': typeof StaffUpdateRoute
  '/tasks/permissions': typeof TasksPermissionsRoute
  '/tasks/reports': typeof TasksReportsRoute
  '/tasks/setup': typeof TasksSetupRoute
  '/regulations/': typeof RegulationsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approval-requests': typeof ApprovalRequestsRoute
  '/auth': typeof AuthRoute
  '/correspondence': typeof CorrespondenceRoute
  '/end-of-service-provision': typeof EndOfServiceProvisionRoute
  '/end-of-service-requests': typeof EndOfServiceRequestsRoute
  '/inquiries': typeof InquiriesRoute
  '/leaves': typeof LeavesRoute
  '/loans': typeof LoansRoute
  '/payroll': typeof PayrollRouteWithChildren
  '/permissions': typeof PermissionsRoute
  '/permits': typeof PermitsRoute
  '/request-notifications': typeof RequestNotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/surveys': typeof SurveysRoute
  '/vacations': typeof VacationsRoute
  '/payroll/bank-file': typeof PayrollBankFileRoute
  '/regulations/approvals': typeof RegulationsApprovalsRoute
  '/regulations/bank-fees': typeof RegulationsBankFeesRoute
  '/regulations/deductions': typeof RegulationsDeductionsRoute
  '/regulations/eos': typeof RegulationsEosRoute
  '/regulations/fingerprint': typeof RegulationsFingerprintRoute
  '/regulations/loans': typeof RegulationsLoansRoute
  '/regulations/other': typeof RegulationsOtherRoute
  '/regulations/permits': typeof RegulationsPermitsRoute
  '/regulations/shifts': typeof RegulationsShiftsRoute
  '/regulations/vacations': typeof RegulationsVacationsRoute
  '/reports/absence-daily': typeof ReportsAbsenceDailyRoute
  '/reports/absence-days-count': typeof ReportsAbsenceDaysCountRoute
  '/reports/absence-days-list': typeof ReportsAbsenceDaysListRoute
  '/reports/absence-employee': typeof ReportsAbsenceEmployeeRoute
  '/reports/absence-late-comparison': typeof ReportsAbsenceLateComparisonRoute
  '/reports/absence-monthly': typeof ReportsAbsenceMonthlyRoute
  '/reports/absence-value': typeof ReportsAbsenceValueRoute
  '/reports/admin-forms': typeof ReportsAdminFormsRoute
  '/reports/archive': typeof ReportsArchiveRoute
  '/reports/attendance': typeof ReportsAttendanceRoute
  '/reports/attendance-comprehensive': typeof ReportsAttendanceComprehensiveRoute
  '/reports/attendance-detailed': typeof ReportsAttendanceDetailedRoute
  '/reports/attendance-statistics': typeof ReportsAttendanceStatisticsRoute
  '/reports/bank-statement': typeof ReportsBankStatementRoute
  '/reports/basic-data': typeof ReportsBasicDataRoute
  '/reports/daily-late': typeof ReportsDailyLateRoute
  '/reports/early-checkout-days': typeof ReportsEarlyCheckoutDaysRoute
  '/reports/employee-account-statement': typeof ReportsEmployeeAccountStatementRoute
  '/reports/employee-certificates': typeof ReportsEmployeeCertificatesRoute
  '/reports/employee-contracts-report': typeof ReportsEmployeeContractsReportRoute
  '/reports/employee-data': typeof ReportsEmployeeDataRoute
  '/reports/employee-dependents': typeof ReportsEmployeeDependentsRoute
  '/reports/employee-files': typeof ReportsEmployeeFilesRoute
  '/reports/employee-headcount': typeof ReportsEmployeeHeadcountRoute
  '/reports/employee-leaves': typeof ReportsEmployeeLeavesRoute
  '/reports/employee-training': typeof ReportsEmployeeTrainingRoute
  '/reports/entitlements-deductions': typeof ReportsEntitlementsDeductionsRoute
  '/reports/evaluation': typeof ReportsEvaluationRoute
  '/reports/exceptions': typeof ReportsExceptionsRoute
  '/reports/financial-data': typeof ReportsFinancialDataRoute
  '/reports/fingerprint': typeof ReportsFingerprintRoute
  '/reports/hire-and-termination': typeof ReportsHireAndTerminationRoute
  '/reports/historical-leaves': typeof ReportsHistoricalLeavesRoute
  '/reports/late-days-list': typeof ReportsLateDaysListRoute
  '/reports/late-minutes': typeof ReportsLateMinutesRoute
  '/reports/loans-balance': typeof ReportsLoansBalanceRoute
  '/reports/loans-data': typeof ReportsLoansDataRoute
  '/reports/manpower-budget': typeof ReportsManpowerBudgetRoute
  '/reports/medical-insurance': typeof ReportsMedicalInsuranceRoute
  '/reports/payroll-adjustments': typeof ReportsPayrollAdjustmentsRoute
  '/reports/payroll-comparison': typeof ReportsPayrollComparisonRoute
  '/reports/payroll-sheet': typeof ReportsPayrollSheetRoute
  '/reports/petty-cash': typeof ReportsPettyCashRoute
  '/reports/requests-summary': typeof ReportsRequestsSummaryRoute
  '/reports/surveys-report': typeof ReportsSurveysReportRoute
  '/requests/purchase-budget': typeof RequestsPurchaseBudgetRoute
  '/requests/setup': typeof RequestsSetupRoute
  '/settings/account-links': typeof SettingsAccountLinksRoute
  '/settings/basic': typeof SettingsBasicRoute
  '/settings/branch-quotas': typeof SettingsBranchQuotasRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/calendar': typeof SettingsCalendarRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/company-documents': typeof SettingsCompanyDocumentsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/sponsors': typeof SettingsSponsorsRoute
  '/settings/suspension-reasons': typeof SettingsSuspensionReasonsRoute
  '/shifts/approvals': typeof ShiftsApprovalsRoute
  '/shifts/audit': typeof ShiftsAuditRoute
  '/shifts/bindings': typeof ShiftsBindingsRoute
  '/shifts/coverage': typeof ShiftsCoverageRoute
  '/shifts/exceptions': typeof ShiftsExceptionsRoute
  '/shifts/import': typeof ShiftsImportRoute
  '/shifts/library': typeof ShiftsLibraryRoute
  '/shifts/mine': typeof ShiftsMineRoute
  '/shifts/open': typeof ShiftsOpenRoute
  '/shifts/patterns': typeof ShiftsPatternsRoute
  '/shifts/policies': typeof ShiftsPoliciesRoute
  '/shifts/reports': typeof ShiftsReportsRoute
  '/shifts/requests': typeof ShiftsRequestsRoute
  '/shifts/rosters': typeof ShiftsRostersRoute
  '/shifts/templates': typeof ShiftsTemplatesRoute
  '/staff/add': typeof StaffAddRoute
  '/staff/bank-block': typeof StaffBankBlockRoute
  '/staff/contracts': typeof StaffContractsRoute
  '/staff/manager': typeof StaffManagerRoute
  '/staff/transfer': typeof StaffTransferRoute
  '/staff/update': typeof StaffUpdateRoute
  '/tasks/permissions': typeof TasksPermissionsRoute
  '/tasks/reports': typeof TasksReportsRoute
  '/tasks/setup': typeof TasksSetupRoute
  '/regulations': typeof RegulationsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approval-requests': typeof ApprovalRequestsRoute
  '/auth': typeof AuthRoute
  '/correspondence': typeof CorrespondenceRoute
  '/end-of-service-provision': typeof EndOfServiceProvisionRoute
  '/end-of-service-requests': typeof EndOfServiceRequestsRoute
  '/inquiries': typeof InquiriesRoute
  '/leaves': typeof LeavesRoute
  '/loans': typeof LoansRoute
  '/payroll': typeof PayrollRouteWithChildren
  '/permissions': typeof PermissionsRoute
  '/permits': typeof PermitsRoute
  '/regulations': typeof RegulationsRouteWithChildren
  '/request-notifications': typeof RequestNotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/surveys': typeof SurveysRoute
  '/vacations': typeof VacationsRoute
  '/payroll/bank-file': typeof PayrollBankFileRoute
  '/regulations/approvals': typeof RegulationsApprovalsRoute
  '/regulations/bank-fees': typeof RegulationsBankFeesRoute
  '/regulations/deductions': typeof RegulationsDeductionsRoute
  '/regulations/eos': typeof RegulationsEosRoute
  '/regulations/fingerprint': typeof RegulationsFingerprintRoute
  '/regulations/loans': typeof RegulationsLoansRoute
  '/regulations/other': typeof RegulationsOtherRoute
  '/regulations/permits': typeof RegulationsPermitsRoute
  '/regulations/shifts': typeof RegulationsShiftsRoute
  '/regulations/vacations': typeof RegulationsVacationsRoute
  '/reports/absence-daily': typeof ReportsAbsenceDailyRoute
  '/reports/absence-days-count': typeof ReportsAbsenceDaysCountRoute
  '/reports/absence-days-list': typeof ReportsAbsenceDaysListRoute
  '/reports/absence-employee': typeof ReportsAbsenceEmployeeRoute
  '/reports/absence-late-comparison': typeof ReportsAbsenceLateComparisonRoute
  '/reports/absence-monthly': typeof ReportsAbsenceMonthlyRoute
  '/reports/absence-value': typeof ReportsAbsenceValueRoute
  '/reports/admin-forms': typeof ReportsAdminFormsRoute
  '/reports/archive': typeof ReportsArchiveRoute
  '/reports/attendance': typeof ReportsAttendanceRoute
  '/reports/attendance-comprehensive': typeof ReportsAttendanceComprehensiveRoute
  '/reports/attendance-detailed': typeof ReportsAttendanceDetailedRoute
  '/reports/attendance-statistics': typeof ReportsAttendanceStatisticsRoute
  '/reports/bank-statement': typeof ReportsBankStatementRoute
  '/reports/basic-data': typeof ReportsBasicDataRoute
  '/reports/daily-late': typeof ReportsDailyLateRoute
  '/reports/early-checkout-days': typeof ReportsEarlyCheckoutDaysRoute
  '/reports/employee-account-statement': typeof ReportsEmployeeAccountStatementRoute
  '/reports/employee-certificates': typeof ReportsEmployeeCertificatesRoute
  '/reports/employee-contracts-report': typeof ReportsEmployeeContractsReportRoute
  '/reports/employee-data': typeof ReportsEmployeeDataRoute
  '/reports/employee-dependents': typeof ReportsEmployeeDependentsRoute
  '/reports/employee-files': typeof ReportsEmployeeFilesRoute
  '/reports/employee-headcount': typeof ReportsEmployeeHeadcountRoute
  '/reports/employee-leaves': typeof ReportsEmployeeLeavesRoute
  '/reports/employee-training': typeof ReportsEmployeeTrainingRoute
  '/reports/entitlements-deductions': typeof ReportsEntitlementsDeductionsRoute
  '/reports/evaluation': typeof ReportsEvaluationRoute
  '/reports/exceptions': typeof ReportsExceptionsRoute
  '/reports/financial-data': typeof ReportsFinancialDataRoute
  '/reports/fingerprint': typeof ReportsFingerprintRoute
  '/reports/hire-and-termination': typeof ReportsHireAndTerminationRoute
  '/reports/historical-leaves': typeof ReportsHistoricalLeavesRoute
  '/reports/late-days-list': typeof ReportsLateDaysListRoute
  '/reports/late-minutes': typeof ReportsLateMinutesRoute
  '/reports/loans-balance': typeof ReportsLoansBalanceRoute
  '/reports/loans-data': typeof ReportsLoansDataRoute
  '/reports/manpower-budget': typeof ReportsManpowerBudgetRoute
  '/reports/medical-insurance': typeof ReportsMedicalInsuranceRoute
  '/reports/payroll-adjustments': typeof ReportsPayrollAdjustmentsRoute
  '/reports/payroll-comparison': typeof ReportsPayrollComparisonRoute
  '/reports/payroll-sheet': typeof ReportsPayrollSheetRoute
  '/reports/petty-cash': typeof ReportsPettyCashRoute
  '/reports/requests-summary': typeof ReportsRequestsSummaryRoute
  '/reports/surveys-report': typeof ReportsSurveysReportRoute
  '/requests/purchase-budget': typeof RequestsPurchaseBudgetRoute
  '/requests/setup': typeof RequestsSetupRoute
  '/settings/account-links': typeof SettingsAccountLinksRoute
  '/settings/basic': typeof SettingsBasicRoute
  '/settings/branch-quotas': typeof SettingsBranchQuotasRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/calendar': typeof SettingsCalendarRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/company-documents': typeof SettingsCompanyDocumentsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/sponsors': typeof SettingsSponsorsRoute
  '/settings/suspension-reasons': typeof SettingsSuspensionReasonsRoute
  '/shifts/approvals': typeof ShiftsApprovalsRoute
  '/shifts/audit': typeof ShiftsAuditRoute
  '/shifts/bindings': typeof ShiftsBindingsRoute
  '/shifts/coverage': typeof ShiftsCoverageRoute
  '/shifts/exceptions': typeof ShiftsExceptionsRoute
  '/shifts/import': typeof ShiftsImportRoute
  '/shifts/library': typeof ShiftsLibraryRoute
  '/shifts/mine': typeof ShiftsMineRoute
  '/shifts/open': typeof ShiftsOpenRoute
  '/shifts/patterns': typeof ShiftsPatternsRoute
  '/shifts/policies': typeof ShiftsPoliciesRoute
  '/shifts/reports': typeof ShiftsReportsRoute
  '/shifts/requests': typeof ShiftsRequestsRoute
  '/shifts/rosters': typeof ShiftsRostersRoute
  '/shifts/templates': typeof ShiftsTemplatesRoute
  '/staff/add': typeof StaffAddRoute
  '/staff/bank-block': typeof StaffBankBlockRoute
  '/staff/contracts': typeof StaffContractsRoute
  '/staff/manager': typeof StaffManagerRoute
  '/staff/transfer': typeof StaffTransferRoute
  '/staff/update': typeof StaffUpdateRoute
  '/tasks/permissions': typeof TasksPermissionsRoute
  '/tasks/reports': typeof TasksReportsRoute
  '/tasks/setup': typeof TasksSetupRoute
  '/regulations/': typeof RegulationsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approval-requests'
    | '/auth'
    | '/correspondence'
    | '/end-of-service-provision'
    | '/end-of-service-requests'
    | '/inquiries'
    | '/leaves'
    | '/loans'
    | '/payroll'
    | '/permissions'
    | '/permits'
    | '/regulations'
    | '/request-notifications'
    | '/reset-password'
    | '/settings'
    | '/staff'
    | '/surveys'
    | '/vacations'
    | '/payroll/bank-file'
    | '/regulations/approvals'
    | '/regulations/bank-fees'
    | '/regulations/deductions'
    | '/regulations/eos'
    | '/regulations/fingerprint'
    | '/regulations/loans'
    | '/regulations/other'
    | '/regulations/permits'
    | '/regulations/shifts'
    | '/regulations/vacations'
    | '/reports/absence-daily'
    | '/reports/absence-days-count'
    | '/reports/absence-days-list'
    | '/reports/absence-employee'
    | '/reports/absence-late-comparison'
    | '/reports/absence-monthly'
    | '/reports/absence-value'
    | '/reports/admin-forms'
    | '/reports/archive'
    | '/reports/attendance'
    | '/reports/attendance-comprehensive'
    | '/reports/attendance-detailed'
    | '/reports/attendance-statistics'
    | '/reports/bank-statement'
    | '/reports/basic-data'
    | '/reports/daily-late'
    | '/reports/early-checkout-days'
    | '/reports/employee-account-statement'
    | '/reports/employee-certificates'
    | '/reports/employee-contracts-report'
    | '/reports/employee-data'
    | '/reports/employee-dependents'
    | '/reports/employee-files'
    | '/reports/employee-headcount'
    | '/reports/employee-leaves'
    | '/reports/employee-training'
    | '/reports/entitlements-deductions'
    | '/reports/evaluation'
    | '/reports/exceptions'
    | '/reports/financial-data'
    | '/reports/fingerprint'
    | '/reports/hire-and-termination'
    | '/reports/historical-leaves'
    | '/reports/late-days-list'
    | '/reports/late-minutes'
    | '/reports/loans-balance'
    | '/reports/loans-data'
    | '/reports/manpower-budget'
    | '/reports/medical-insurance'
    | '/reports/payroll-adjustments'
    | '/reports/payroll-comparison'
    | '/reports/payroll-sheet'
    | '/reports/petty-cash'
    | '/reports/requests-summary'
    | '/reports/surveys-report'
    | '/requests/purchase-budget'
    | '/requests/setup'
    | '/settings/account-links'
    | '/settings/basic'
    | '/settings/branch-quotas'
    | '/settings/branches'
    | '/settings/calendar'
    | '/settings/company'
    | '/settings/company-documents'
    | '/settings/general'
    | '/settings/sponsors'
    | '/settings/suspension-reasons'
    | '/shifts/approvals'
    | '/shifts/audit'
    | '/shifts/bindings'
    | '/shifts/coverage'
    | '/shifts/exceptions'
    | '/shifts/import'
    | '/shifts/library'
    | '/shifts/mine'
    | '/shifts/open'
    | '/shifts/patterns'
    | '/shifts/policies'
    | '/shifts/reports'
    | '/shifts/requests'
    | '/shifts/rosters'
    | '/shifts/templates'
    | '/staff/add'
    | '/staff/bank-block'
    | '/staff/contracts'
    | '/staff/manager'
    | '/staff/transfer'
    | '/staff/update'
    | '/tasks/permissions'
    | '/tasks/reports'
    | '/tasks/setup'
    | '/regulations/'
    | '/staff/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approval-requests'
    | '/auth'
    | '/correspondence'
    | '/end-of-service-provision'
    | '/end-of-service-requests'
    | '/inquiries'
    | '/leaves'
    | '/loans'
    | '/payroll'
    | '/permissions'
    | '/permits'
    | '/request-notifications'
    | '/reset-password'
    | '/settings'
    | '/surveys'
    | '/vacations'
    | '/payroll/bank-file'
    | '/regulations/approvals'
    | '/regulations/bank-fees'
    | '/regulations/deductions'
    | '/regulations/eos'
    | '/regulations/fingerprint'
    | '/regulations/loans'
    | '/regulations/other'
    | '/regulations/permits'
    | '/regulations/shifts'
    | '/regulations/vacations'
    | '/reports/absence-daily'
    | '/reports/absence-days-count'
    | '/reports/absence-days-list'
    | '/reports/absence-employee'
    | '/reports/absence-late-comparison'
    | '/reports/absence-monthly'
    | '/reports/absence-value'
    | '/reports/admin-forms'
    | '/reports/archive'
    | '/reports/attendance'
    | '/reports/attendance-comprehensive'
    | '/reports/attendance-detailed'
    | '/reports/attendance-statistics'
    | '/reports/bank-statement'
    | '/reports/basic-data'
    | '/reports/daily-late'
    | '/reports/early-checkout-days'
    | '/reports/employee-account-statement'
    | '/reports/employee-certificates'
    | '/reports/employee-contracts-report'
    | '/reports/employee-data'
    | '/reports/employee-dependents'
    | '/reports/employee-files'
    | '/reports/employee-headcount'
    | '/reports/employee-leaves'
    | '/reports/employee-training'
    | '/reports/entitlements-deductions'
    | '/reports/evaluation'
    | '/reports/exceptions'
    | '/reports/financial-data'
    | '/reports/fingerprint'
    | '/reports/hire-and-termination'
    | '/reports/historical-leaves'
    | '/reports/late-days-list'
    | '/reports/late-minutes'
    | '/reports/loans-balance'
    | '/reports/loans-data'
    | '/reports/manpower-budget'
    | '/reports/medical-insurance'
    | '/reports/payroll-adjustments'
    | '/reports/payroll-comparison'
    | '/reports/payroll-sheet'
    | '/reports/petty-cash'
    | '/reports/requests-summary'
    | '/reports/surveys-report'
    | '/requests/purchase-budget'
    | '/requests/setup'
    | '/settings/account-links'
    | '/settings/basic'
    | '/settings/branch-quotas'
    | '/settings/branches'
    | '/settings/calendar'
    | '/settings/company'
    | '/settings/company-documents'
    | '/settings/general'
    | '/settings/sponsors'
    | '/settings/suspension-reasons'
    | '/shifts/approvals'
    | '/shifts/audit'
    | '/shifts/bindings'
    | '/shifts/coverage'
    | '/shifts/exceptions'
    | '/shifts/import'
    | '/shifts/library'
    | '/shifts/mine'
    | '/shifts/open'
    | '/shifts/patterns'
    | '/shifts/policies'
    | '/shifts/reports'
    | '/shifts/requests'
    | '/shifts/rosters'
    | '/shifts/templates'
    | '/staff/add'
    | '/staff/bank-block'
    | '/staff/contracts'
    | '/staff/manager'
    | '/staff/transfer'
    | '/staff/update'
    | '/tasks/permissions'
    | '/tasks/reports'
    | '/tasks/setup'
    | '/regulations'
    | '/staff'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/approval-requests'
    | '/auth'
    | '/correspondence'
    | '/end-of-service-provision'
    | '/end-of-service-requests'
    | '/inquiries'
    | '/leaves'
    | '/loans'
    | '/payroll'
    | '/permissions'
    | '/permits'
    | '/regulations'
    | '/request-notifications'
    | '/reset-password'
    | '/settings'
    | '/staff'
    | '/surveys'
    | '/vacations'
    | '/payroll/bank-file'
    | '/regulations/approvals'
    | '/regulations/bank-fees'
    | '/regulations/deductions'
    | '/regulations/eos'
    | '/regulations/fingerprint'
    | '/regulations/loans'
    | '/regulations/other'
    | '/regulations/permits'
    | '/regulations/shifts'
    | '/regulations/vacations'
    | '/reports/absence-daily'
    | '/reports/absence-days-count'
    | '/reports/absence-days-list'
    | '/reports/absence-employee'
    | '/reports/absence-late-comparison'
    | '/reports/absence-monthly'
    | '/reports/absence-value'
    | '/reports/admin-forms'
    | '/reports/archive'
    | '/reports/attendance'
    | '/reports/attendance-comprehensive'
    | '/reports/attendance-detailed'
    | '/reports/attendance-statistics'
    | '/reports/bank-statement'
    | '/reports/basic-data'
    | '/reports/daily-late'
    | '/reports/early-checkout-days'
    | '/reports/employee-account-statement'
    | '/reports/employee-certificates'
    | '/reports/employee-contracts-report'
    | '/reports/employee-data'
    | '/reports/employee-dependents'
    | '/reports/employee-files'
    | '/reports/employee-headcount'
    | '/reports/employee-leaves'
    | '/reports/employee-training'
    | '/reports/entitlements-deductions'
    | '/reports/evaluation'
    | '/reports/exceptions'
    | '/reports/financial-data'
    | '/reports/fingerprint'
    | '/reports/hire-and-termination'
    | '/reports/historical-leaves'
    | '/reports/late-days-list'
    | '/reports/late-minutes'
    | '/reports/loans-balance'
    | '/reports/loans-data'
    | '/reports/manpower-budget'
    | '/reports/medical-insurance'
    | '/reports/payroll-adjustments'
    | '/reports/payroll-comparison'
    | '/reports/payroll-sheet'
    | '/reports/petty-cash'
    | '/reports/requests-summary'
    | '/reports/surveys-report'
    | '/requests/purchase-budget'
    | '/requests/setup'
    | '/settings/account-links'
    | '/settings/basic'
    | '/settings/branch-quotas'
    | '/settings/branches'
    | '/settings/calendar'
    | '/settings/company'
    | '/settings/company-documents'
    | '/settings/general'
    | '/settings/sponsors'
    | '/settings/suspension-reasons'
    | '/shifts/approvals'
    | '/shifts/audit'
    | '/shifts/bindings'
    | '/shifts/coverage'
    | '/shifts/exceptions'
    | '/shifts/import'
    | '/shifts/library'
    | '/shifts/mine'
    | '/shifts/open'
    | '/shifts/patterns'
    | '/shifts/policies'
    | '/shifts/reports'
    | '/shifts/requests'
    | '/shifts/rosters'
    | '/shifts/templates'
    | '/staff/add'
    | '/staff/bank-block'
    | '/staff/contracts'
    | '/staff/manager'
    | '/staff/transfer'
    | '/staff/update'
    | '/tasks/permissions'
    | '/tasks/reports'
    | '/tasks/setup'
    | '/regulations/'
    | '/staff/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalRequestsRoute: typeof ApprovalRequestsRoute
  AuthRoute: typeof AuthRoute
  CorrespondenceRoute: typeof CorrespondenceRoute
  EndOfServiceProvisionRoute: typeof EndOfServiceProvisionRoute
  EndOfServiceRequestsRoute: typeof EndOfServiceRequestsRoute
  InquiriesRoute: typeof InquiriesRoute
  LeavesRoute: typeof LeavesRoute
  LoansRoute: typeof LoansRoute
  PayrollRoute: typeof PayrollRouteWithChildren
  PermissionsRoute: typeof PermissionsRoute
  PermitsRoute: typeof PermitsRoute
  RegulationsRoute: typeof RegulationsRouteWithChildren
  RequestNotificationsRoute: typeof RequestNotificationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  SurveysRoute: typeof SurveysRoute
  VacationsRoute: typeof VacationsRoute
  ReportsAbsenceDailyRoute: typeof ReportsAbsenceDailyRoute
  ReportsAbsenceDaysCountRoute: typeof ReportsAbsenceDaysCountRoute
  ReportsAbsenceDaysListRoute: typeof ReportsAbsenceDaysListRoute
  ReportsAbsenceEmployeeRoute: typeof ReportsAbsenceEmployeeRoute
  ReportsAbsenceLateComparisonRoute: typeof ReportsAbsenceLateComparisonRoute
  ReportsAbsenceMonthlyRoute: typeof ReportsAbsenceMonthlyRoute
  ReportsAbsenceValueRoute: typeof ReportsAbsenceValueRoute
  ReportsAdminFormsRoute: typeof ReportsAdminFormsRoute
  ReportsArchiveRoute: typeof ReportsArchiveRoute
  ReportsAttendanceRoute: typeof ReportsAttendanceRoute
  ReportsAttendanceComprehensiveRoute: typeof ReportsAttendanceComprehensiveRoute
  ReportsAttendanceDetailedRoute: typeof ReportsAttendanceDetailedRoute
  ReportsAttendanceStatisticsRoute: typeof ReportsAttendanceStatisticsRoute
  ReportsBankStatementRoute: typeof ReportsBankStatementRoute
  ReportsBasicDataRoute: typeof ReportsBasicDataRoute
  ReportsDailyLateRoute: typeof ReportsDailyLateRoute
  ReportsEarlyCheckoutDaysRoute: typeof ReportsEarlyCheckoutDaysRoute
  ReportsEmployeeAccountStatementRoute: typeof ReportsEmployeeAccountStatementRoute
  ReportsEmployeeCertificatesRoute: typeof ReportsEmployeeCertificatesRoute
  ReportsEmployeeContractsReportRoute: typeof ReportsEmployeeContractsReportRoute
  ReportsEmployeeDataRoute: typeof ReportsEmployeeDataRoute
  ReportsEmployeeDependentsRoute: typeof ReportsEmployeeDependentsRoute
  ReportsEmployeeFilesRoute: typeof ReportsEmployeeFilesRoute
  ReportsEmployeeHeadcountRoute: typeof ReportsEmployeeHeadcountRoute
  ReportsEmployeeLeavesRoute: typeof ReportsEmployeeLeavesRoute
  ReportsEmployeeTrainingRoute: typeof ReportsEmployeeTrainingRoute
  ReportsEntitlementsDeductionsRoute: typeof ReportsEntitlementsDeductionsRoute
  ReportsEvaluationRoute: typeof ReportsEvaluationRoute
  ReportsExceptionsRoute: typeof ReportsExceptionsRoute
  ReportsFinancialDataRoute: typeof ReportsFinancialDataRoute
  ReportsFingerprintRoute: typeof ReportsFingerprintRoute
  ReportsHireAndTerminationRoute: typeof ReportsHireAndTerminationRoute
  ReportsHistoricalLeavesRoute: typeof ReportsHistoricalLeavesRoute
  ReportsLateDaysListRoute: typeof ReportsLateDaysListRoute
  ReportsLateMinutesRoute: typeof ReportsLateMinutesRoute
  ReportsLoansBalanceRoute: typeof ReportsLoansBalanceRoute
  ReportsLoansDataRoute: typeof ReportsLoansDataRoute
  ReportsManpowerBudgetRoute: typeof ReportsManpowerBudgetRoute
  ReportsMedicalInsuranceRoute: typeof ReportsMedicalInsuranceRoute
  ReportsPayrollAdjustmentsRoute: typeof ReportsPayrollAdjustmentsRoute
  ReportsPayrollComparisonRoute: typeof ReportsPayrollComparisonRoute
  ReportsPayrollSheetRoute: typeof ReportsPayrollSheetRoute
  ReportsPettyCashRoute: typeof ReportsPettyCashRoute
  ReportsRequestsSummaryRoute: typeof ReportsRequestsSummaryRoute
  ReportsSurveysReportRoute: typeof ReportsSurveysReportRoute
  RequestsPurchaseBudgetRoute: typeof RequestsPurchaseBudgetRoute
  RequestsSetupRoute: typeof RequestsSetupRoute
  ShiftsApprovalsRoute: typeof ShiftsApprovalsRoute
  ShiftsAuditRoute: typeof ShiftsAuditRoute
  ShiftsBindingsRoute: typeof ShiftsBindingsRoute
  ShiftsCoverageRoute: typeof ShiftsCoverageRoute
  ShiftsExceptionsRoute: typeof ShiftsExceptionsRoute
  ShiftsImportRoute: typeof ShiftsImportRoute
  ShiftsLibraryRoute: typeof ShiftsLibraryRoute
  ShiftsMineRoute: typeof ShiftsMineRoute
  ShiftsOpenRoute: typeof ShiftsOpenRoute
  ShiftsPatternsRoute: typeof ShiftsPatternsRoute
  ShiftsPoliciesRoute: typeof ShiftsPoliciesRoute
  ShiftsReportsRoute: typeof ShiftsReportsRoute
  ShiftsRequestsRoute: typeof ShiftsRequestsRoute
  ShiftsRostersRoute: typeof ShiftsRostersRoute
  ShiftsTemplatesRoute: typeof ShiftsTemplatesRoute
  TasksPermissionsRoute: typeof TasksPermissionsRoute
  TasksReportsRoute: typeof TasksReportsRoute
  TasksSetupRoute: typeof TasksSetupRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-requests': {
      id: '/approval-requests'
      path: '/approval-requests'
      fullPath: '/approval-requests'
      preLoaderRoute: typeof ApprovalRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correspondence': {
      id: '/correspondence'
      path: '/correspondence'
      fullPath: '/correspondence'
      preLoaderRoute: typeof CorrespondenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/end-of-service-provision': {
      id: '/end-of-service-provision'
      path: '/end-of-service-provision'
      fullPath: '/end-of-service-provision'
      preLoaderRoute: typeof EndOfServiceProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/end-of-service-requests': {
      id: '/end-of-service-requests'
      path: '/end-of-service-requests'
      fullPath: '/end-of-service-requests'
      preLoaderRoute: typeof EndOfServiceRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries': {
      id: '/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof InquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permits': {
      id: '/permits'
      path: '/permits'
      fullPath: '/permits'
      preLoaderRoute: typeof PermitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulations': {
      id: '/regulations'
      path: '/regulations'
      fullPath: '/regulations'
      preLoaderRoute: typeof RegulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-notifications': {
      id: '/request-notifications'
      path: '/request-notifications'
      fullPath: '/request-notifications'
      preLoaderRoute: typeof RequestNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacations': {
      id: '/vacations'
      path: '/vacations'
      fullPath: '/vacations'
      preLoaderRoute: typeof VacationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll/bank-file': {
      id: '/payroll/bank-file'
      path: '/bank-file'
      fullPath: '/payroll/bank-file'
      preLoaderRoute: typeof PayrollBankFileRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/regulations/': {
      id: '/regulations/'
      path: '/'
      fullPath: '/regulations/'
      preLoaderRoute: typeof RegulationsIndexRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/approvals': {
      id: '/regulations/approvals'
      path: '/approvals'
      fullPath: '/regulations/approvals'
      preLoaderRoute: typeof RegulationsApprovalsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/bank-fees': {
      id: '/regulations/bank-fees'
      path: '/bank-fees'
      fullPath: '/regulations/bank-fees'
      preLoaderRoute: typeof RegulationsBankFeesRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/deductions': {
      id: '/regulations/deductions'
      path: '/deductions'
      fullPath: '/regulations/deductions'
      preLoaderRoute: typeof RegulationsDeductionsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/eos': {
      id: '/regulations/eos'
      path: '/eos'
      fullPath: '/regulations/eos'
      preLoaderRoute: typeof RegulationsEosRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/fingerprint': {
      id: '/regulations/fingerprint'
      path: '/fingerprint'
      fullPath: '/regulations/fingerprint'
      preLoaderRoute: typeof RegulationsFingerprintRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/loans': {
      id: '/regulations/loans'
      path: '/loans'
      fullPath: '/regulations/loans'
      preLoaderRoute: typeof RegulationsLoansRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/other': {
      id: '/regulations/other'
      path: '/other'
      fullPath: '/regulations/other'
      preLoaderRoute: typeof RegulationsOtherRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/permits': {
      id: '/regulations/permits'
      path: '/permits'
      fullPath: '/regulations/permits'
      preLoaderRoute: typeof RegulationsPermitsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/shifts': {
      id: '/regulations/shifts'
      path: '/shifts'
      fullPath: '/regulations/shifts'
      preLoaderRoute: typeof RegulationsShiftsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/vacations': {
      id: '/regulations/vacations'
      path: '/vacations'
      fullPath: '/regulations/vacations'
      preLoaderRoute: typeof RegulationsVacationsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/reports/absence-daily': {
      id: '/reports/absence-daily'
      path: '/reports/absence-daily'
      fullPath: '/reports/absence-daily'
      preLoaderRoute: typeof ReportsAbsenceDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/absence-days-count': {
      id: '/reports/absence-days-count'
      path: '/reports/absence-days-count'
      fullPath: '/reports/absence-days-count'
      preLoaderRoute: typeof ReportsAbsenceDaysCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/absence-days-list': {
      id: '/reports/absence-days-list'
      path: '/reports/absence-days-list'
      fullPath: '/reports/absence-days-list'
      preLoaderRoute: typeof ReportsAbsenceDaysListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/absence-employee': {
      id: '/reports/absence-employee'
      path: '/reports/absence-employee'
      fullPath: '/reports/absence-employee'
      preLoaderRoute: typeof ReportsAbsenceEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/absence-late-comparison': {
      id: '/reports/absence-late-comparison'
      path: '/reports/absence-late-comparison'
      fullPath: '/reports/absence-late-comparison'
      preLoaderRoute: typeof ReportsAbsenceLateComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/absence-monthly': {
      id: '/reports/absence-monthly'
      path: '/reports/absence-monthly'
      fullPath: '/reports/absence-monthly'
      preLoaderRoute: typeof ReportsAbsenceMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/absence-value': {
      id: '/reports/absence-value'
      path: '/reports/absence-value'
      fullPath: '/reports/absence-value'
      preLoaderRoute: typeof ReportsAbsenceValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/admin-forms': {
      id: '/reports/admin-forms'
      path: '/reports/admin-forms'
      fullPath: '/reports/admin-forms'
      preLoaderRoute: typeof ReportsAdminFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/archive': {
      id: '/reports/archive'
      path: '/reports/archive'
      fullPath: '/reports/archive'
      preLoaderRoute: typeof ReportsArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/attendance': {
      id: '/reports/attendance'
      path: '/reports/attendance'
      fullPath: '/reports/attendance'
      preLoaderRoute: typeof ReportsAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/attendance-comprehensive': {
      id: '/reports/attendance-comprehensive'
      path: '/reports/attendance-comprehensive'
      fullPath: '/reports/attendance-comprehensive'
      preLoaderRoute: typeof ReportsAttendanceComprehensiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/attendance-detailed': {
      id: '/reports/attendance-detailed'
      path: '/reports/attendance-detailed'
      fullPath: '/reports/attendance-detailed'
      preLoaderRoute: typeof ReportsAttendanceDetailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/attendance-statistics': {
      id: '/reports/attendance-statistics'
      path: '/reports/attendance-statistics'
      fullPath: '/reports/attendance-statistics'
      preLoaderRoute: typeof ReportsAttendanceStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/bank-statement': {
      id: '/reports/bank-statement'
      path: '/reports/bank-statement'
      fullPath: '/reports/bank-statement'
      preLoaderRoute: typeof ReportsBankStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/basic-data': {
      id: '/reports/basic-data'
      path: '/reports/basic-data'
      fullPath: '/reports/basic-data'
      preLoaderRoute: typeof ReportsBasicDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/daily-late': {
      id: '/reports/daily-late'
      path: '/reports/daily-late'
      fullPath: '/reports/daily-late'
      preLoaderRoute: typeof ReportsDailyLateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/early-checkout-days': {
      id: '/reports/early-checkout-days'
      path: '/reports/early-checkout-days'
      fullPath: '/reports/early-checkout-days'
      preLoaderRoute: typeof ReportsEarlyCheckoutDaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/employee-account-statement': {
      id: '/reports/employee-account-statement'
      path: '/reports/employee-account-statement'
      fullPath: '/reports/employee-account-statement'
      preLoaderRoute: typeof ReportsEmployeeAccountStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/employee-certificates': {
      id: '/reports/employee-certificates'
      path: '/reports/employee-certificates'
      fullPath: '/reports/employee-certificates'
      preLoaderRoute: typeof ReportsEmployeeCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/employee-contracts-report': {
      id: '/reports/employee-contracts-report'
      path: '/reports/employee-contracts-report'
      fullPath: '/reports/employee-contracts-report'
      preLoaderRoute: typeof ReportsEmployeeContractsReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/employee-data': {
      id: '/reports/employee-data'
      path: '/reports/employee-data'
      fullPath: '/reports/employee-data'
      preLoaderRoute: typeof ReportsEmployeeDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/employee-dependents': {
      id: '/reports/employee-dependents'
      path: '/reports/employee-dependents'
      fullPath: '/reports/employee-dependents'
      preLoaderRoute: typeof ReportsEmployeeDependentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/employee-files': {
      id: '/reports/employee-files'
      path: '/reports/employee-files'
      fullPath: '/reports/employee-files'
      preLoaderRoute: typeof ReportsEmployeeFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/employee-headcount': {
      id: '/reports/employee-headcount'
      path: '/reports/employee-headcount'
      fullPath: '/reports/employee-headcount'
      preLoaderRoute: typeof ReportsEmployeeHeadcountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/employee-leaves': {
      id: '/reports/employee-leaves'
      path: '/reports/employee-leaves'
      fullPath: '/reports/employee-leaves'
      preLoaderRoute: typeof ReportsEmployeeLeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/employee-training': {
      id: '/reports/employee-training'
      path: '/reports/employee-training'
      fullPath: '/reports/employee-training'
      preLoaderRoute: typeof ReportsEmployeeTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/entitlements-deductions': {
      id: '/reports/entitlements-deductions'
      path: '/reports/entitlements-deductions'
      fullPath: '/reports/entitlements-deductions'
      preLoaderRoute: typeof ReportsEntitlementsDeductionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/evaluation': {
      id: '/reports/evaluation'
      path: '/reports/evaluation'
      fullPath: '/reports/evaluation'
      preLoaderRoute: typeof ReportsEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/exceptions': {
      id: '/reports/exceptions'
      path: '/reports/exceptions'
      fullPath: '/reports/exceptions'
      preLoaderRoute: typeof ReportsExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/financial-data': {
      id: '/reports/financial-data'
      path: '/reports/financial-data'
      fullPath: '/reports/financial-data'
      preLoaderRoute: typeof ReportsFinancialDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/fingerprint': {
      id: '/reports/fingerprint'
      path: '/reports/fingerprint'
      fullPath: '/reports/fingerprint'
      preLoaderRoute: typeof ReportsFingerprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/hire-and-termination': {
      id: '/reports/hire-and-termination'
      path: '/reports/hire-and-termination'
      fullPath: '/reports/hire-and-termination'
      preLoaderRoute: typeof ReportsHireAndTerminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/historical-leaves': {
      id: '/reports/historical-leaves'
      path: '/reports/historical-leaves'
      fullPath: '/reports/historical-leaves'
      preLoaderRoute: typeof ReportsHistoricalLeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/late-days-list': {
      id: '/reports/late-days-list'
      path: '/reports/late-days-list'
      fullPath: '/reports/late-days-list'
      preLoaderRoute: typeof ReportsLateDaysListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/late-minutes': {
      id: '/reports/late-minutes'
      path: '/reports/late-minutes'
      fullPath: '/reports/late-minutes'
      preLoaderRoute: typeof ReportsLateMinutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/loans-balance': {
      id: '/reports/loans-balance'
      path: '/reports/loans-balance'
      fullPath: '/reports/loans-balance'
      preLoaderRoute: typeof ReportsLoansBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/loans-data': {
      id: '/reports/loans-data'
      path: '/reports/loans-data'
      fullPath: '/reports/loans-data'
      preLoaderRoute: typeof ReportsLoansDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/manpower-budget': {
      id: '/reports/manpower-budget'
      path: '/reports/manpower-budget'
      fullPath: '/reports/manpower-budget'
      preLoaderRoute: typeof ReportsManpowerBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/medical-insurance': {
      id: '/reports/medical-insurance'
      path: '/reports/medical-insurance'
      fullPath: '/reports/medical-insurance'
      preLoaderRoute: typeof ReportsMedicalInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/payroll-adjustments': {
      id: '/reports/payroll-adjustments'
      path: '/reports/payroll-adjustments'
      fullPath: '/reports/payroll-adjustments'
      preLoaderRoute: typeof ReportsPayrollAdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/payroll-comparison': {
      id: '/reports/payroll-comparison'
      path: '/reports/payroll-comparison'
      fullPath: '/reports/payroll-comparison'
      preLoaderRoute: typeof ReportsPayrollComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/payroll-sheet': {
      id: '/reports/payroll-sheet'
      path: '/reports/payroll-sheet'
      fullPath: '/reports/payroll-sheet'
      preLoaderRoute: typeof ReportsPayrollSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/petty-cash': {
      id: '/reports/petty-cash'
      path: '/reports/petty-cash'
      fullPath: '/reports/petty-cash'
      preLoaderRoute: typeof ReportsPettyCashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/requests-summary': {
      id: '/reports/requests-summary'
      path: '/reports/requests-summary'
      fullPath: '/reports/requests-summary'
      preLoaderRoute: typeof ReportsRequestsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/surveys-report': {
      id: '/reports/surveys-report'
      path: '/reports/surveys-report'
      fullPath: '/reports/surveys-report'
      preLoaderRoute: typeof ReportsSurveysReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/purchase-budget': {
      id: '/requests/purchase-budget'
      path: '/requests/purchase-budget'
      fullPath: '/requests/purchase-budget'
      preLoaderRoute: typeof RequestsPurchaseBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/setup': {
      id: '/requests/setup'
      path: '/requests/setup'
      fullPath: '/requests/setup'
      preLoaderRoute: typeof RequestsSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account-links': {
      id: '/settings/account-links'
      path: '/account-links'
      fullPath: '/settings/account-links'
      preLoaderRoute: typeof SettingsAccountLinksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/basic': {
      id: '/settings/basic'
      path: '/basic'
      fullPath: '/settings/basic'
      preLoaderRoute: typeof SettingsBasicRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/branch-quotas': {
      id: '/settings/branch-quotas'
      path: '/branch-quotas'
      fullPath: '/settings/branch-quotas'
      preLoaderRoute: typeof SettingsBranchQuotasRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/branches': {
      id: '/settings/branches'
      path: '/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof SettingsBranchesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/calendar': {
      id: '/settings/calendar'
      path: '/calendar'
      fullPath: '/settings/calendar'
      preLoaderRoute: typeof SettingsCalendarRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/company': {
      id: '/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof SettingsCompanyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/company-documents': {
      id: '/settings/company-documents'
      path: '/company-documents'
      fullPath: '/settings/company-documents'
      preLoaderRoute: typeof SettingsCompanyDocumentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sponsors': {
      id: '/settings/sponsors'
      path: '/sponsors'
      fullPath: '/settings/sponsors'
      preLoaderRoute: typeof SettingsSponsorsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/suspension-reasons': {
      id: '/settings/suspension-reasons'
      path: '/suspension-reasons'
      fullPath: '/settings/suspension-reasons'
      preLoaderRoute: typeof SettingsSuspensionReasonsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/shifts/approvals': {
      id: '/shifts/approvals'
      path: '/shifts/approvals'
      fullPath: '/shifts/approvals'
      preLoaderRoute: typeof ShiftsApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/audit': {
      id: '/shifts/audit'
      path: '/shifts/audit'
      fullPath: '/shifts/audit'
      preLoaderRoute: typeof ShiftsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/bindings': {
      id: '/shifts/bindings'
      path: '/shifts/bindings'
      fullPath: '/shifts/bindings'
      preLoaderRoute: typeof ShiftsBindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/coverage': {
      id: '/shifts/coverage'
      path: '/shifts/coverage'
      fullPath: '/shifts/coverage'
      preLoaderRoute: typeof ShiftsCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/exceptions': {
      id: '/shifts/exceptions'
      path: '/shifts/exceptions'
      fullPath: '/shifts/exceptions'
      preLoaderRoute: typeof ShiftsExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/import': {
      id: '/shifts/import'
      path: '/shifts/import'
      fullPath: '/shifts/import'
      preLoaderRoute: typeof ShiftsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/library': {
      id: '/shifts/library'
      path: '/shifts/library'
      fullPath: '/shifts/library'
      preLoaderRoute: typeof ShiftsLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/mine': {
      id: '/shifts/mine'
      path: '/shifts/mine'
      fullPath: '/shifts/mine'
      preLoaderRoute: typeof ShiftsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/open': {
      id: '/shifts/open'
      path: '/shifts/open'
      fullPath: '/shifts/open'
      preLoaderRoute: typeof ShiftsOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/patterns': {
      id: '/shifts/patterns'
      path: '/shifts/patterns'
      fullPath: '/shifts/patterns'
      preLoaderRoute: typeof ShiftsPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/policies': {
      id: '/shifts/policies'
      path: '/shifts/policies'
      fullPath: '/shifts/policies'
      preLoaderRoute: typeof ShiftsPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/reports': {
      id: '/shifts/reports'
      path: '/shifts/reports'
      fullPath: '/shifts/reports'
      preLoaderRoute: typeof ShiftsReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/requests': {
      id: '/shifts/requests'
      path: '/shifts/requests'
      fullPath: '/shifts/requests'
      preLoaderRoute: typeof ShiftsRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/rosters': {
      id: '/shifts/rosters'
      path: '/shifts/rosters'
      fullPath: '/shifts/rosters'
      preLoaderRoute: typeof ShiftsRostersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/templates': {
      id: '/shifts/templates'
      path: '/shifts/templates'
      fullPath: '/shifts/templates'
      preLoaderRoute: typeof ShiftsTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/add': {
      id: '/staff/add'
      path: '/add'
      fullPath: '/staff/add'
      preLoaderRoute: typeof StaffAddRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/bank-block': {
      id: '/staff/bank-block'
      path: '/bank-block'
      fullPath: '/staff/bank-block'
      preLoaderRoute: typeof StaffBankBlockRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/contracts': {
      id: '/staff/contracts'
      path: '/contracts'
      fullPath: '/staff/contracts'
      preLoaderRoute: typeof StaffContractsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/manager': {
      id: '/staff/manager'
      path: '/manager'
      fullPath: '/staff/manager'
      preLoaderRoute: typeof StaffManagerRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/transfer': {
      id: '/staff/transfer'
      path: '/transfer'
      fullPath: '/staff/transfer'
      preLoaderRoute: typeof StaffTransferRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/update': {
      id: '/staff/update'
      path: '/update'
      fullPath: '/staff/update'
      preLoaderRoute: typeof StaffUpdateRouteImport
      parentRoute: typeof StaffRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/permissions': {
      id: '/tasks/permissions'
      path: '/tasks/permissions'
      fullPath: '/tasks/permissions'
      preLoaderRoute: typeof TasksPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/reports': {
      id: '/tasks/reports'
      path: '/tasks/reports'
      fullPath: '/tasks/reports'
      preLoaderRoute: typeof TasksReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/setup': {
      id: '/tasks/setup'
      path: '/tasks/setup'
      fullPath: '/tasks/setup'
      preLoaderRoute: typeof TasksSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PayrollRouteChildren {
  PayrollBankFileRoute: typeof PayrollBankFileRoute
}

const PayrollRouteChildren: PayrollRouteChildren = {
  PayrollBankFileRoute: PayrollBankFileRoute,
}

const PayrollRouteWithChildren =
  PayrollRoute._addFileChildren(PayrollRouteChildren)

interface RegulationsRouteChildren {
  RegulationsApprovalsRoute: typeof RegulationsApprovalsRoute
  RegulationsBankFeesRoute: typeof RegulationsBankFeesRoute
  RegulationsDeductionsRoute: typeof RegulationsDeductionsRoute
  RegulationsEosRoute: typeof RegulationsEosRoute
  RegulationsFingerprintRoute: typeof RegulationsFingerprintRoute
  RegulationsLoansRoute: typeof RegulationsLoansRoute
  RegulationsOtherRoute: typeof RegulationsOtherRoute
  RegulationsPermitsRoute: typeof RegulationsPermitsRoute
  RegulationsShiftsRoute: typeof RegulationsShiftsRoute
  RegulationsVacationsRoute: typeof RegulationsVacationsRoute
  RegulationsIndexRoute: typeof RegulationsIndexRoute
}

const RegulationsRouteChildren: RegulationsRouteChildren = {
  RegulationsApprovalsRoute: RegulationsApprovalsRoute,
  RegulationsBankFeesRoute: RegulationsBankFeesRoute,
  RegulationsDeductionsRoute: RegulationsDeductionsRoute,
  RegulationsEosRoute: RegulationsEosRoute,
  RegulationsFingerprintRoute: RegulationsFingerprintRoute,
  RegulationsLoansRoute: RegulationsLoansRoute,
  RegulationsOtherRoute: RegulationsOtherRoute,
  RegulationsPermitsRoute: RegulationsPermitsRoute,
  RegulationsShiftsRoute: RegulationsShiftsRoute,
  RegulationsVacationsRoute: RegulationsVacationsRoute,
  RegulationsIndexRoute: RegulationsIndexRoute,
}

const RegulationsRouteWithChildren = RegulationsRoute._addFileChildren(
  RegulationsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAccountLinksRoute: typeof SettingsAccountLinksRoute
  SettingsBasicRoute: typeof SettingsBasicRoute
  SettingsBranchQuotasRoute: typeof SettingsBranchQuotasRoute
  SettingsBranchesRoute: typeof SettingsBranchesRoute
  SettingsCalendarRoute: typeof SettingsCalendarRoute
  SettingsCompanyRoute: typeof SettingsCompanyRoute
  SettingsCompanyDocumentsRoute: typeof SettingsCompanyDocumentsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsSponsorsRoute: typeof SettingsSponsorsRoute
  SettingsSuspensionReasonsRoute: typeof SettingsSuspensionReasonsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountLinksRoute: SettingsAccountLinksRoute,
  SettingsBasicRoute: SettingsBasicRoute,
  SettingsBranchQuotasRoute: SettingsBranchQuotasRoute,
  SettingsBranchesRoute: SettingsBranchesRoute,
  SettingsCalendarRoute: SettingsCalendarRoute,
  SettingsCompanyRoute: SettingsCompanyRoute,
  SettingsCompanyDocumentsRoute: SettingsCompanyDocumentsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsSponsorsRoute: SettingsSponsorsRoute,
  SettingsSuspensionReasonsRoute: SettingsSuspensionReasonsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface StaffRouteChildren {
  StaffAddRoute: typeof StaffAddRoute
  StaffBankBlockRoute: typeof StaffBankBlockRoute
  StaffContractsRoute: typeof StaffContractsRoute
  StaffManagerRoute: typeof StaffManagerRoute
  StaffTransferRoute: typeof StaffTransferRoute
  StaffUpdateRoute: typeof StaffUpdateRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAddRoute: StaffAddRoute,
  StaffBankBlockRoute: StaffBankBlockRoute,
  StaffContractsRoute: StaffContractsRoute,
  StaffManagerRoute: StaffManagerRoute,
  StaffTransferRoute: StaffTransferRoute,
  StaffUpdateRoute: StaffUpdateRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalRequestsRoute: ApprovalRequestsRoute,
  AuthRoute: AuthRoute,
  CorrespondenceRoute: CorrespondenceRoute,
  EndOfServiceProvisionRoute: EndOfServiceProvisionRoute,
  EndOfServiceRequestsRoute: EndOfServiceRequestsRoute,
  InquiriesRoute: InquiriesRoute,
  LeavesRoute: LeavesRoute,
  LoansRoute: LoansRoute,
  PayrollRoute: PayrollRouteWithChildren,
  PermissionsRoute: PermissionsRoute,
  PermitsRoute: PermitsRoute,
  RegulationsRoute: RegulationsRouteWithChildren,
  RequestNotificationsRoute: RequestNotificationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  SurveysRoute: SurveysRoute,
  VacationsRoute: VacationsRoute,
  ReportsAbsenceDailyRoute: ReportsAbsenceDailyRoute,
  ReportsAbsenceDaysCountRoute: ReportsAbsenceDaysCountRoute,
  ReportsAbsenceDaysListRoute: ReportsAbsenceDaysListRoute,
  ReportsAbsenceEmployeeRoute: ReportsAbsenceEmployeeRoute,
  ReportsAbsenceLateComparisonRoute: ReportsAbsenceLateComparisonRoute,
  ReportsAbsenceMonthlyRoute: ReportsAbsenceMonthlyRoute,
  ReportsAbsenceValueRoute: ReportsAbsenceValueRoute,
  ReportsAdminFormsRoute: ReportsAdminFormsRoute,
  ReportsArchiveRoute: ReportsArchiveRoute,
  ReportsAttendanceRoute: ReportsAttendanceRoute,
  ReportsAttendanceComprehensiveRoute: ReportsAttendanceComprehensiveRoute,
  ReportsAttendanceDetailedRoute: ReportsAttendanceDetailedRoute,
  ReportsAttendanceStatisticsRoute: ReportsAttendanceStatisticsRoute,
  ReportsBankStatementRoute: ReportsBankStatementRoute,
  ReportsBasicDataRoute: ReportsBasicDataRoute,
  ReportsDailyLateRoute: ReportsDailyLateRoute,
  ReportsEarlyCheckoutDaysRoute: ReportsEarlyCheckoutDaysRoute,
  ReportsEmployeeAccountStatementRoute: ReportsEmployeeAccountStatementRoute,
  ReportsEmployeeCertificatesRoute: ReportsEmployeeCertificatesRoute,
  ReportsEmployeeContractsReportRoute: ReportsEmployeeContractsReportRoute,
  ReportsEmployeeDataRoute: ReportsEmployeeDataRoute,
  ReportsEmployeeDependentsRoute: ReportsEmployeeDependentsRoute,
  ReportsEmployeeFilesRoute: ReportsEmployeeFilesRoute,
  ReportsEmployeeHeadcountRoute: ReportsEmployeeHeadcountRoute,
  ReportsEmployeeLeavesRoute: ReportsEmployeeLeavesRoute,
  ReportsEmployeeTrainingRoute: ReportsEmployeeTrainingRoute,
  ReportsEntitlementsDeductionsRoute: ReportsEntitlementsDeductionsRoute,
  ReportsEvaluationRoute: ReportsEvaluationRoute,
  ReportsExceptionsRoute: ReportsExceptionsRoute,
  ReportsFinancialDataRoute: ReportsFinancialDataRoute,
  ReportsFingerprintRoute: ReportsFingerprintRoute,
  ReportsHireAndTerminationRoute: ReportsHireAndTerminationRoute,
  ReportsHistoricalLeavesRoute: ReportsHistoricalLeavesRoute,
  ReportsLateDaysListRoute: ReportsLateDaysListRoute,
  ReportsLateMinutesRoute: ReportsLateMinutesRoute,
  ReportsLoansBalanceRoute: ReportsLoansBalanceRoute,
  ReportsLoansDataRoute: ReportsLoansDataRoute,
  ReportsManpowerBudgetRoute: ReportsManpowerBudgetRoute,
  ReportsMedicalInsuranceRoute: ReportsMedicalInsuranceRoute,
  ReportsPayrollAdjustmentsRoute: ReportsPayrollAdjustmentsRoute,
  ReportsPayrollComparisonRoute: ReportsPayrollComparisonRoute,
  ReportsPayrollSheetRoute: ReportsPayrollSheetRoute,
  ReportsPettyCashRoute: ReportsPettyCashRoute,
  ReportsRequestsSummaryRoute: ReportsRequestsSummaryRoute,
  ReportsSurveysReportRoute: ReportsSurveysReportRoute,
  RequestsPurchaseBudgetRoute: RequestsPurchaseBudgetRoute,
  RequestsSetupRoute: RequestsSetupRoute,
  ShiftsApprovalsRoute: ShiftsApprovalsRoute,
  ShiftsAuditRoute: ShiftsAuditRoute,
  ShiftsBindingsRoute: ShiftsBindingsRoute,
  ShiftsCoverageRoute: ShiftsCoverageRoute,
  ShiftsExceptionsRoute: ShiftsExceptionsRoute,
  ShiftsImportRoute: ShiftsImportRoute,
  ShiftsLibraryRoute: ShiftsLibraryRoute,
  ShiftsMineRoute: ShiftsMineRoute,
  ShiftsOpenRoute: ShiftsOpenRoute,
  ShiftsPatternsRoute: ShiftsPatternsRoute,
  ShiftsPoliciesRoute: ShiftsPoliciesRoute,
  ShiftsReportsRoute: ShiftsReportsRoute,
  ShiftsRequestsRoute: ShiftsRequestsRoute,
  ShiftsRostersRoute: ShiftsRostersRoute,
  ShiftsTemplatesRoute: ShiftsTemplatesRoute,
  TasksPermissionsRoute: TasksPermissionsRoute,
  TasksReportsRoute: TasksReportsRoute,
  TasksSetupRoute: TasksSetupRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
